### ISSUE TITLE
Consider enabling Control Flow Guard

### ISSUE THREAD

**Issue by asvc** [bailey27/cppcryptfs#101]
As `cppcryptfs` is being built with VS2019, would you consider compiling it with [control flow guard](https://docs.microsoft.com/en-us/windows/win32/secbp/control-flow-guard)?

[`/guard:cf` flag](https://docs.microsoft.com/en-us/cpp/build/reference/guard-enable-control-flow-guard?view=vs-2019)

Amongst obvious benefits might help to reduce number of issues like https://github.com/bailey27/cppcryptfs/issues/100 :)

**Comment by bailey27** [comment]
Thanks for pointing out this flag.  I'll do that for the next release.

**Comment by bailey27** [comment]
I enabled it for release builds.  The new release 1.4.2.1 is built using it.

I also started using the /HIGHENTROPYVA linker option for 64-bit.

Thanks again for making me aware of control flow guard.

**Comment by bailey27** [comment]
I also built openssl with /gaurd:cf for this release.
