### ISSUE TITLE
A simple Go (golang) program not working

### ISSUE THREAD

**Issue by bradiso** [bailey27/cppcryptfs#102]
Hi,

Here is a simple program failing in an encrypted folder.

OS : Windows 7 x64
cppcryptfs : 1.4.2.1 x64
Dokany : 1.3.1.1000
Storage : SSD
Go : 1.13.12 x64
Settings : 5 threads, I/O buffer 64kB, Cache TTL : 10s, case insensitive, AES256-EME, long file names, AES256-GCM

Works in a regular folder (not encrypted). On file creation it's ok but on file append it fails : can be empty file or cyclic redundancy error.

Thanks

```
package main

import (
	"os"
)

func main() {
	var (
		f *os.File
		err error
	)

	filename := "wrong.log"

	_, err = os.Stat(filename)
	if os.IsNotExist(err) {
		f, err = os.OpenFile(filename, os.O_CREATE, os.ModePerm)
		if err != nil {
			panic(err)
		}
	} else {
		f, err = os.OpenFile(filename, os.O_APPEND, os.ModePerm)
		if err != nil {
			panic(err)
		}
	}

	_, err = f.Write([]byte("a line\n"))
	if err != nil {
		panic(err)
	}

	f.Close()
}
```

**Comment by bailey27** [comment]
This appears to be the same problem as https://github.com/bailey27/cppcryptfs/issues/99

The fix I implemented for that seems to solve this one too (repeated runs of  the go program don't return an error anymore).

I plan to release the fix in the next few days.

**Comment by bradiso** [comment]
Nice, thanks !

For information, according to https://github.com/golang/go/issues/21322, it looks like I misused the flags with os.OpenFile.

It works on Windows but it's not the recommanded way to do.

So I replaced with a cleaner call, but wrong behavior again, and it fails even on file creation.

```
	filename := "wrong.log"
	/*
	_, err = os.Stat(filename)
	if os.IsNotExist(err) {
		f, err = os.OpenFile(filename, os.O_CREATE, os.ModePerm)
		if err != nil {
			panic(err)
		}
	} else {
		f, err = os.OpenFile(filename, os.O_APPEND, os.ModePerm)
		if err != nil {
			panic(err)
		}
	}
	*/
	f, err = os.OpenFile(filename, os.O_WRONLY|os.O_CREATE|os.O_APPEND, os.ModePerm)
	if err != nil {
		panic(err)
	}
```

**Comment by bailey27** [comment]
When I build and run the version above, I get no error output and wrong.log is always 0 bytes.

It happens both with a cppcryptfs volume and a normal drive.

**Comment by bradiso** [comment]
I suppose you skipped the f.Write line. Indeed, OpenFile does not create an error but Write does.

This is full source

Anyway I think you got it with your patch.

Thanks

```
package main

import (
	"os"
)

func main() {
	var (
		f *os.File
		err error
	)

	filename := "wrong.log"

	f, err = os.OpenFile(filename, os.O_WRONLY|os.O_CREATE|os.O_APPEND, os.ModePerm)
	if err != nil {
		panic(err)
	}

	_, err = f.Write([]byte("a line\n"))
	if err != nil {
		panic(err)
	}

	f.Close()
}
```

**Comment by bailey27** [comment]
You're right, I skipped the write line.  🤦‍♂️

**Comment by bailey27** [comment]
The version above fails with the release version and not with the patch.

**Comment by bailey27** [comment]
The release with the fix is out.  https://github.com/bailey27/cppcryptfs/releases/tag/1.4.2.2
