### ISSUE TITLE
HashCheck

### ISSUE THREAD

**Issue by bradiso** [bailey27/cppcryptfs#103]
HashCheck (https://github.com/gurnec/HashCheck) produces an empty file on "Create Checksum File" in an encrypted folder. It works when create the checksum file in a regular folder even if "checksumed" files are encrypted.

OS : Windows 7 x64
cppcryptfs : 1.4.2.1 x64
Dokany : 1.3.1.1000
Storage : SSD
Settings : 5 threads, I/O buffer 64kB, Cache TTL : 10s, case insensitive, AES256-EME, long file names, AES256-GCM

Thanks

**Comment by bailey27** [comment]
This also appears to be the same problem as #99.

I get an empty file with the release cppcryptfs, and with my fix for #99 I get the expected checksum file.

I hope to release the fix this weekend.

**Comment by bailey27** [comment]
The release with the fix is out.  https://github.com/bailey27/cppcryptfs/releases/tag/1.4.2.2
