### ISSUE TITLE
[Feature request]

### ISSUE THREAD

**Issue by midshipmanorg** [bailey27/cppcryptfs#105]
In my case I use a directory that is encrypted by gocryptfs and synchronized on both Windows and Linux. However, parts of this "vault" contain things (software among others) that I don't need under Linux. Therefore a selective synchronization of the subfolders would be very practical. I could of course disable file name encryption, but I've had some problems with that when I copied files (which I think aren't encrypted) to another place outside the "vault". 

It would be great if encrypted files/directories could be uniquely marked to maintain readability.

Let's say you got an unencrypted document with the name "document.tex" which gets encrypted to document.tex.gc
instead of A5W5e4Uj8CTvIJEy29aB8w

**Comment by bailey27** [comment]
You can use cppcryptfctl -l to find the encrypted name of the directory and then tell your syncing software to exclude it from syncing.

e.g.

C:\>cppcryptfsctl -lh:\ | findstr /i windows
windows_binaries => gH5nKU8sc1ZtfbGczs4LpbnJLwtBCHJpTMkAnKz0Yy0
