### ISSUE TITLE
[Q] Gocryptfs compatibility: can cppcryptfs work with -plaintextnames filesystems?

### ISSUE THREAD

**Issue by jpluscplusm** [bailey27/cppcryptfs#107]
Hi there,

Apologies for overloading the "Issues" concept, but this seemed the best way to both ask this question and get the answer stored for future searchers :-) I'm writing up a use-case of Gocryptfs on Mac/Linux, but don't have a Windows machine to test on ...

Can cppcryptfs mount, work with, and leave in a happy state for future Gocryptfs-on-Linux use, a filesystem created with the `-plaintextnames` option?

I ask this as I note that this project's README states "cppcryptfs requires the [...] EMENames [...] feature flag", and my reading of the source suggests that this feature, whilst once optional, is now unavoidable under Gocryptfs and is filename-related... but I don't know how it interacts with the `plaintextnames` feature.

Can I do the following?

```shell
linux$ gocryptfs -init -plaintextnames /mnt/network/jcm/encrypted
linux$ gocryptfs /mnt/network/jcm/encrypted /home/jcm/secrets
linux$ echo "aSecret" > /home/jcm/secrets/aFile
linux$ [ unmount FS ]
```

and then on a windows machine:

```cmd
C:\> [ mount FS ]
C:\> [ do something with aFile ]
```

**Comment by bailey27** [comment]
I'm sorry for the confusion.  In its early days, gocryptfs supported another file name encryption method besides EME which cppcryptfs never supported.  That is why that statement is there.  

This does not apply to plain text filenames.  

You should be able to do what you intend to do with gocryptfs and cppcryptfs.

**Comment by bailey27** [comment]
I've updated the documentation.

**Comment by jpluscplusm** [comment]
Many thanks - that's just what I needed to find out :-)
