### ISSUE TITLE
Folder content disappearing on move/copy/replace 

### ISSUE THREAD

**Issue by loungebob** [bailey27/cppcryptfs#111]
I've been having this issue for years but I usually work around it through intermediate folders but sometimes I forget and then it annoys the living out of me.

Windows 10, Windows File Explorer, Google Drive File Stream and Google Drive. All up to date.

Here's what happens:
When I move a folder that already exists in the place it is moved to and explorer asks if I want to merge folders and possibly replace content within and I say yes, I get asked what I want to do if there is a file or files with the same name already in the destination folder. I usually chose keep both files so explorer adds (2) to the end of the file that is being copied into the destination folder.
Now, if there is no file in the destination folder, windows explorer just copies the content from source to destination folder. 
In this case, the file disappears straight away. I mean, I hit refresh and the destination folder is empty. even though explorer just copied a file into it. This also happens if I delete the original file from the destination folder after the source file had been copied into (and got (2) added to the filename) and rename the (2) file to the filename of the file I just deleted. I hit refresh and the file is gone.
I can get the file back when I undo the moving/copying operation or manually move the folder back to it's original location. Refresh and voilà, the files are back.
This strangely also happens if I rename the destination folder to lets say blabla_TOBEDELETED, then delete the folder or move it to another folder so it's out of the way and no longer within the original structure, then copy/move the source folder (with the same name but naturally without the _TOBEDELETED part) to the original structure and then check the contents, all gone.
Somewhere something remembers stuff too long and wrongly. Is this the file system on top of another file system stuff?

I can work around it if I chose intermediate folders to move stuff around. But only if the folder name didnt exist in the final destination folder in the first place. Then I need to chose a new name for the source folder or stuff disappears.

Did this make any sense at all lol?

**Comment by bailey27** [comment]
I think this probably happens because of caching in cppcryptfs.

I would first try going on the settings tab and changing "Cache time to live" to 1 second.  You can't completely disable all caching, unfortunately.  The default is 10 seconds.

Another thing I would try is disabling "Case insensitive".  That will probably cause some programs not to work, but Windows File Explorer doesn't seem to have a problem.  The case insensitive setting uses caching, so turning that off will disable that cache.

For the settings to take effect, you have to unmount and re-mount the filesystem.  cppcryptfs uses whatever settings were in effect when the filesystem was mounted.

If that doesn't help, then I would do a test with a file system created with plaintext file names and see if the problem still happens with that.

**Comment by loungebob** [comment]
ok, I’ll try that and report back. this isnt the caching I see in windows explorer though, is it? what does your caching influence?
I was wondering where I should look for windows explorer caching. I have a lot of the details columns in explorer active for movies and images (like resolution, bitdepth, codec...). sometimes explorer displays those results instantly when going into a folder and having its contents displayed in file explorer but most of the times it takes like 20-30 seconds depending on how many files are in a folder and how large they are for explorer to display its content and explorer freezes up until it finishes. if i disable those additional columns the results are always displayed instantly without the delay. I wonder where that caching is and how to manipulate it. would you know?

**Comment by bailey27** [comment]
The caching I'm referring to is all in cppcryptfs.

One thing I noticed really helps file explorer speed (not just with cppcryptfs) is turning on the setting "Launch folder windows in a separate process".


![image](https://user-images.githubusercontent.com/17813578/93714817-1b692180-fb33-11ea-9a35-f728d211b324.png)

**Comment by loungebob** [comment]
havent had time to test it much but changing the caching from infinite to something more sensible seems to solve this issue. however, what is the data that was actually being cached by cpp? since I havent tested it much yet, where would I see performance impact by reducing the cache time to live?
also, something entirely different, I'm unable to find where I can see the decrypted master key (the one I should copy and keep safe :-) )

**Comment by bailey27** [comment]
The performance should be ok with a TLL of 1 second.  I use 10 seconds and can't measure any difference between that an infinite in the things I've timed.  I don't remember timing 1 second TTL, but I didn't notice it being slower than 10 either.

cppcryptfs caches the diriv files when it's in forward mode.  If you have case insensitive turned on, then it caches contents of recently accessed directories so it can figure out what the actual cases of the filenames are.  It has to use the exact case of the filenames when encrypting them.

You can't currently print the master key.  I'll add an option to cppcryptfsctl to print the master key after providing the password.

**Comment by loungebob** [comment]
I see you implemented the print master key feature. However I'm unable to find it. Is that not a GUI thing?
