### ISSUE TITLE
Screen controls tab order and alt-W shortcut unexpected

### ISSUE THREAD

**Issue by jimmbelll** [bailey27/cppcryptfs#117]
On the Mount tab, the screen controls' tab ordering is mixed up. In particular, alt-W which should take you to the password entry doesn't do that.

As others have said, thanks for an outstanding piece of software!

**Comment by bailey27** [comment]
Thanks for pointing this out.  It will be fixed in the next release.

**Comment by bailey27** [comment]
The new release should fix this.
