### ISSUE TITLE
I lost gocryptfs.diriv

### ISSUE THREAD

**Issue by 6677028** [bailey27/cppcryptfs#127]
Dear Sr
 I lost gocryptfs.diriv. I have masterkey and gocryptfs.conf.
 You can hepl me.

**Comment by bailey27** [comment]
gocryptfs.diriv is used (combined with the master key) to encrypt the names of the files and directories in the directory/folder that contains that gocryptfs.diriv.  

If you lose it, you can't recover the names.  You can recover the data, though.  You can also recover the names of any files and directories that were under that folder as long as those directories still have their gocryptfs.diriv.

I am assuming you lost the gocryptfs.diriv in your root directory (at the top of the filesystem).

The way you can recover the files is to do this:

To recover files from the directory with missing gocryptfs.diriv:

1. First, *make a backup of the whole encrypted fs* (the encrypted files and directories) while it is unmounted.  You can just copy it all to a folder somewhere.
2. Edit gocryptfs.conf (you'll need to remove the read-only attribute) and change the line that says "EMENames", to say "PlaintextNames", (the comma is important).
3. Delete the line that says "DirIV",
4. Mount the filesystem.  From the mounted filesystem (fs), move (not copy) the files, not the directories, to some folder on your system.
5. The data is unencrypted, but the files still have the encrypted file names.  You'll probably want some tool like the "file" command from cygwin or one of the tools mentioned here https://superuser.com/questions/274734/how-can-i-determine-file-type-without-an-extension-on-windows to figure out what type the files are.  If you find out a file is a PDF, then rename it with .pdf extension, etc.  Then you can open the files and see what is in them and rename them.

Then umount the fs and put back the original gocrypfs.conf.

Create a new scratch filesystem similar to the one you're dealing with. Copy the gocryptfs.diriv from its root  into the the directory you're fixing so it now has a gocryptfs.diriv.

To recover the directories:

1. move the encrypted directories somewhere
2. mount the filesystem, and for each directory that was there, create a placeholder directory (e.g. named 1, 2, 3, etc.).
3. *umount* the filesystem.
4. go to the first directory you moved out of your fs and move its contents (the contents, not the directory itself) into a placeholder directory you created (the fs unmounted now).  The directory you're moving to should have only a gocryptfs.diriv in it.  Overwrite the gocryptfs.diriv when moving the contents you saved previously.  You want the old gocryptfs.diriv, in other words.
5. Repeat with the other directories, moving the contents of each one into its own placeholder directory, overwriting the gocryptfs.diriv in the placeholder directory.

When you've done this, if you mount the filesystem, you should have directories with names e.g. 1, 2, 3, and under them will be the files and directories you moved under there with their normal names.

**Comment by 6677028** [comment]
Ok.
 I lost only gocryptfs.diriv external folder. Folder inside, i have gocryptfs.diriv. So I just copy all the folders inside to the outer folder. It is ok
 gocryptfs.diriv and gocryptfs.conf, I can upload cloud, Am I afraid of losing information?

**Comment by bailey27** [comment]
I'm not sure what you mean by losing information.  The gocryptfs.diriv files are not sensitive.  It doesn't matter if somebody else can see them.  They can't use them to decrypt your data without the master key.  The master key is safe in gocryptfs.conf if your password is strong.

**Comment by 6677028** [comment]
With this software yours. We will have a lot of gocryptfs.diriv files. If gocryptfs.diriv is corrupted, virus or lost, we will lose data. Therefore, the level of data loss will be higher.
 In the future you can remove these files and just use a Masterkey. Then I only need to save a Masterkey file, When there is a problem, I already have the masterkey file and I can reopen my data.
 Thank you.

**Comment by bailey27** [comment]
You are right.  Losing the gocryptfs.diriv in a directory that contains lots of files and/or subdirectories would be quite a challenge to recover from.

gocryptfs/cppcryptfs does generate the diriv files on-the-fly and deterministically when in reverse mode which uses AES-SIV.  It would be possible to do this also in forward mode when using AES-SIV, but gocryptfs did not implement it this way.  There was some talk in the gocryptfs issue tracker about this, but as far as I can tell, it was never done.  The links to the issues are below.

https://github.com/rfjakob/gocryptfs/issues/108
https://github.com/bailey27/cppcryptfs/issues/15


What I do is periodically make backups of my data.  I use tar and gpg from cygwin.  I use the symmetric mode of gpg with AES-256 as the encryption algorithm.  This way if anything goes wrong in my encrypted fs, I can use the latest backup.  I've never had to use a backup, though.  I've never lost a diriv file either.

**Comment by 6677028** [comment]
OK thank you. I'm deciding between cppcryptfs and cryptomator
