### ISSUE TITLE
Broken file is not copied from the decrypted folder 

### ISSUE THREAD

**Issue by atom44** [bailey27/cppcryptfs#128]
I was recording streaming video to google drive folder via the attached file system - AirLiveDrive, files in this program are first written to the cache folder, and then to the Google cloud itself, there was a break in the Internet, a file from the cache folder AirLiveDrive, did not have time to copy to the encrypted folder cppcryptfs, when the internet recovered, I manually copied the encrypted file from the cache folder AirLiveDrive in the encrypted folder of the google drive, in which all the files are encrypted exactly - cppcryptfs, in the decrypted folder, the file appeared and you can even see a preview, but the problem is that the video file is only 6 seconds long, but it should be at least 30 minutes, the video is broken, I would like to restore it using special programs, but the decrypted file does not want to be copied anywhere , writes "Unable to read from file or disk." What to do? how to copy it decrypted? The file, as I understand it, does not want to be decrypted due to the fact that it is broken.  Win 7x32, DokanLibrary-1.4.1.

**Comment by bailey27** [comment]
I think what happened was there is some corruption in the encrypted file. When cppcryptfs encounters data corruption, it returns a CRC error.  Most programs will give up if they encounter an error when copying a file.

I would try getting cygwin (https://cygwin.com/install.html) and using the dd command and tell it to copy the file ignoring errors.

For example, if your unencrypted view of the file is in K:\foo\boo\myvideo.mp4

Run cygwin bash shell, then

cd /cygdrive/k/foo/boo

dd if=myvideo.mp4 of=myvideo_copy.mp4 conv=sync,noerror bs=4096

I tried this on a small mp4 (18MB).  I intentionally changed a byte of the encrypted data.  Normal copying failed with a CRC error, but when I copied it using the above command, the copied video was playable.
