### ISSUE TITLE
Clear entries under mount path

### ISSUE THREAD

**Issue by markzajac** [bailey27/cppcryptfs#129]
Hello. Great project. Is it possible to clear the entries for the path drop down on the mount tab? I have 8 path entries and I would like to delete two of them since I've deleted the underlying folders. They're just creating clutter.  See picture below. Thanks for your time answering my question.  -Z

![cppcryptfs_img1](https://user-images.githubusercontent.com/83355243/123452273-de3f2d80-d5a3-11eb-81f1-ca9c7d802f18.PNG)

**Comment by bailey27** [comment]
Those are stored in the registry.  If you run regedit.exe and go to

Computer\HKEY_CURRENT_USER\SOFTWARE\cppcryptfs\cppcryptfs\Folders

You can delete the the paths there.

**Comment by markzajac** [comment]
Thank you. Closing ticket.
