### ISSUE TITLE
BSOD random after using program

### ISSUE THREAD

**Issue by velteyn** [bailey27/cppcryptfs#137]
Hello,
Im experiencing Blue Screen Of death after using your program in random times.. Unexpected Store Exception 

Il computer è stato riavviato da un controllo errori. Controllo errori: 0x00000154 (0xffffdb8e804ab000, 0xfffff6095299d740, 0x0000000000000001, 0x0000000000000000). I dettagli sono stati salvati in: C:\WINDOWS\MEMORY.DMP. ID segnalazione: 08aac305-414b-464f-8a01-6372d6f11f15.

Memory Dump is very large. 3Gb cannot post here :)
Ho can I help to fined if its related to the program ?
I have the latest version

**Comment by bailey27** [comment]
Hi @velteyn,

cppcryptfs is a user-mode program, so it theoretically shouldn't be able to cause a blue screen crash (which is Windows kernel-mode crash) by itself.

cppcryptfs does use the Dokany kernel-mode driver, so maybe cppcryptfs is causing the Dokany driver to do something it normally doesn't do, which could trigger the blue-screen.

However, the problem could be unrelated to cppcryptfs and have to do only with Dokany.

Could you please see if you can reproduce the blue screen by using the Dokany sample mirror filesystem?

Here is an example usage (in a Windows command prompt window, preferably run as administrator):

```
"C:\Program Files\Dokan\Dokan Library-1.5.0\sample\mirror\mirror.exe" /r c:\tmp\mirror /l M:
```

That would create a drive letter M: that is a view of the contents of the directory c:\tmp\mirror (without encryption).

If you used this drive letter similarly to how you were using cppcryptfs, then seeing if you get the blue screen or don't get the blue screen would help determine if the crash were strictly a Dokany issue or a cppcryptfs+Dokany issue.

Another thing.  If the crash happens soon after mounting, I would try turning off the "enable fast mounting" setting and see if that solves the problem.

**Comment by velteyn** [comment]
Ok, when I'm not using the pc for job  I'll do the test, thank you
