### ISSUE TITLE
filename length 

### ISSUE THREAD

**Issue by BrsyRockSs** [bailey27/cppcryptfs#138]
>Add -longnamemax flag to -init (#499). Can be used to work around file or path length restrictions on online storage. See the man page for details.

>https://github.com/rfjakob/gocryptfs/issues/499

File name length in win system
This problem has been solved in the latest version of GCP
I'm not urging you to update this, just reminding you that if you can update freely, please don't forget this problem

Thank you very much for your work in this regard,
^.^

**Comment by bailey27** [comment]
Thanks for telling me.

I'll definitely be adding this.

**Comment by bailey27** [comment]
This was released in 1.4.3.11
