### ISSUE TITLE
Can't create volume.

### ISSUE THREAD

**Issue by Achaean** [bailey27/cppcryptfs#139]
On "Create" tab, selecting the Path and pressing the "Create" button, doesn't do something.

Latest versions  (1.4.3.10), with Dokany 1.5.0.3000 at Win Pro 11.
Everything 64-bit.

**Comment by bailey27** [comment]
I think this is because you need to input a password.

It does put up a message box if you don't repeat the password, but as I think you observed, it just does nothing if the password field is blank.  I'll make a note to add a message box for that.

**Comment by Achaean** [comment]
Ooops!!! Mea culpa!  :-)
Indeed, I entered an empty pwd.

**Comment by bailey27** [comment]
Fixed in 1.4.3.11 which was just released.
