### ISSUE TITLE
More command line functionality?

### ISSUE THREAD

**Issue by null-python** [bailey27/cppcryptfs#144]
Hi, I was wondering if you could add the ability to pass in a unencrypted directory path to cppcryptfsctl and return the encrypted directory and vice versa

**Comment by bailey27** [comment]
That's a great suggestion.  It will be in the next release (done and testing now).  It works for file paths too.  It takes a full path and returns the plain path if the input path is encrypted and returns the encrypted path if the input path is plain.

**Comment by bailey27** [comment]
This was added to 1.4.3.11.  The command line option is --transform or -M
