### ISSUE TITLE
dokan1.dll couldn't be found (Dokany 2).

### ISSUE THREAD

**Issue by Achaean** [bailey27/cppcryptfs#145]
Probably Dokany v.2 isn't backwards compatible.
Cppcryptfs, prints the message "dokan1.dll couldn't be found" and aborts.

![Screenshot](https://user-images.githubusercontent.com/3608053/147885123-6ca0e70e-a032-4fb8-9bbd-cd1c39f2eadb.png)
At Win 11 Pro x64.
 
**Happy New Year** to everyone!!!  :-)

**Comment by bailey27** [comment]
Yeah, it's not backwards compatible.  I'm looking at the porting guide from 1.x to 2.0 now.

**Comment by bailey27** [comment]
I got it working with Dokany 2.0.  I'll release a new version soon.

**Comment by Achaean** [comment]
**Great!!!**  :-)

Last version (1.43.11), works flawlessly with Dokany v.2.0.0.2000.
