### ISSUE TITLE
Broken mount point when using cppcryptfsctl

### ISSUE THREAD

**Issue by mhogomchungu** [bailey27/cppcryptfs#150]
Versions of apps used:

Windows version: Windows 10
Dokan version: 2.0.1.1000
cppcryptfs: 1.4.3.11 (AlphaTest)
cppcryptfsctl: 1.4.3.11 (AlphaTest)

Command used to successfully unlock a volume
```
C:/Users/blabla/bin/cppcryptfsctl.exe -m C:/Users/blabla/Desktop/cpp -d Y: -p xxx -c C:/Users/blabla/Desktop/cpp/gocryptfs.conf
```

When locking the volume, the locking succeeds but produces an error as seen below

```
C:/Users/blabla/bin/cppcryptfsctl.exe -u Y:
cppcryptfs: Unable to get volume information, The system cannot find the path specified.

```

When trying to access the drive letter, windows produces an error seen below

![Screenshot_20220204_234437](https://user-images.githubusercontent.com/3496115/152604206-3202fe8f-f7bf-4443-ab48-3340bbd4507d.png)

**Comment by bailey27** [comment]
Hi.  I can reproduce the problem if I use forward slashes in the paths as you are.  

If I use backslashes '\' it doesn't happen.  Could you try using back slashes?

**Comment by mhogomchungu** [comment]
It works as expected when using backslashes.
