### ISSUE TITLE
Password in not read through stdin when it is not provided with "-p" CLI option when mounting

### ISSUE THREAD

**Issue by mhogomchungu** [bailey27/cppcryptfs#151]
```
cppcryptfsctl.exe -m C:\Users\blabla\Desktop\secrets -d E:
cppcryptfs: password cannot be empty
```

In the above example, i intentionally did not provide the "-p" option because i want to send the password through stdin and both cppcryptfs and cppcryptfsctl appears to not be able to handle this scenario.

When creating a volume, the process errors out when "-p" option is given as seen below

```
cppcryptfsctl.exe -I C:\Users\blabla\Desktop\yyyy -p ttt
Invalid option. Try 'cppcryptfsctl --help' for more information.
```

It looks like when creating a volume, the only supported option is through stdin and when unlocking a volume, the only supported option is through CLI argument and this seems inconsistent.

It should be possible to pass password through both CLI argument and stdin when creating and unlocking.

**Comment by bailey27** [comment]
Yes, both mounting and initializing should be able to get the password either from the -p option or from stdin.  I'll fix that in the next release.

**Comment by bailey27** [comment]
The latest release 1.4.4.0 fixes this.
