### ISSUE TITLE
Need migrate to new container to implement longnamemax option? thx

### ISSUE THREAD

**Issue by ccchan234** [bailey27/cppcryptfs#152]
hi,

i saw the newest "longnamemax" option could solve the current problem that cppcryptfs can be stored on google drive but not one drive.

i am trying to implement it, but i found the longnamemax option is in the "create" page: (I haven't install the latest)
https://raw.githubusercontent.com/bailey27/cppcryptfs/master/screenshots/screenshot_create.png

I got 24TB files in an "old" cppcfs containers on google drive,
for safety of my data, may I ask the way to implement the longnamemax option?

what i think is,
create a new container using the longnamemax option of about 100,
then copy the files from the old container to the new.

thanks.

**Comment by bailey27** [comment]
Yes, the way to do it would be to create a new filesystem with longnamemax set to the value you want and then copy everything from the old one into it.
