### ISSUE TITLE
Moving gocryptfs.conf and gocryptfs.diriv to a different directory does not work

### ISSUE THREAD

**Issue by san-r** [bailey27/cppcryptfs#156]
By default, **gocryptfs.conf** and **gocryptfs.diriv** are created in the root directory of the encrypted filesystem.

Experiment: I moved the above two files to a different folder, mentioned the path of gocryptfs.conf in the **"Config file (optional)"** text box of the program, and tried to mount. The encrypted file system seemed to mount but the mount point was completely empty!

When I moved the said two files back to the root directory of the encrypted filesystem, the mounting was back to normal.

So is there a proper way to move the said two files to a separate location and still be able to mount properly?

**Comment by yfdyh000** [comment]
gocryptfs.diriv files is used to decrypt encrypted file names.

**Comment by san-r** [comment]
I noticed that if I move just gocryptfs.conf to a different location (and even rename it) and leave gocryptfs.diriv in the root directory of the encrypted filesystem, the mount is normal.

Moving gocryptfs.diriv to a different location does not work. 

It would be nice if the program could work even after changing the location and name of gocryptfs.diriv. Or am I missing something?

**Comment by bailey27** [comment]
The gocryptfs.diriv files are just initialization directories.  They're like salts in that they aren't sensitive even though they're involved in the encryption/decryption process.

When using EME filename encryption, in forward mode, the diriv files are needed, one per directory.  

I plan to add the deterministic filenames in forward mode feature from gocryptfs.  This feature makes the diriv files unnecessary.

**Comment by san-r** [comment]
The presence of any file with the name gocryptfs gives away the encryption method. Being able to change the name to whatever we want would be nice.

**Comment by san-r** [comment]
> The gocryptfs.diriv files are just initialization directories. They're like salts in that they aren't sensitive even though they're involved in the encryption/decryption process.
> 
> When using EME filename encryption, in forward mode, the diriv files are needed, one per directory.
> 
> I plan to add the deterministic filenames in forward mode feature from gocryptfs. This feature makes the diriv files unnecessary.

If the diriv files are made unnecessary, it would add another level of stealth. But please make all newer versions of cppcryptfs compatible with the older versions, ie, users should not need to re-encrypt older volumes. Thank you.

**Comment by san-r** [comment]
Since version 1.4.4.0 features deterministic filenames making diriv files unnecessary, I'm closing this issue.

**Comment by san-r** [comment]
Thanks
