### ISSUE TITLE
Support "HKDF" feature flag

### ISSUE THREAD

**Issue by rfjakob** [bailey27/cppcryptfs#16]
The [security audit](https://defuse.ca/audits/gocryptfs.htm) from March this year suggested that one should not use the same key for GCM content encryption and EME file name encryption.

In gocryptfs v1.3 I have added the "HKDF" feature flag that generates independent keys from the master key for GCM and EME. It basically does
```
emeKey := hash(masterkey + constant1)
gcmKey := hash(masterkey + constant2)
```
"hash" is HKDF-SHA256 from RFC 5869. Code: [cryptocore.go#L66](https://github.com/rfjakob/gocryptfs/blob/d6ef283c3f076ba45dd873d69e1c7d86ed29b14a/internal/cryptocore/cryptocore.go#L66)

I have just grepped for "HKDF" through your repo and not seen it, maybe you want to add support at some point. I just added a few test vectors in [hkdf_test.go](https://github.com/rfjakob/gocryptfs/blob/master/internal/cryptocore/hkdf_test.go), if this helps.

**Comment by bailey27** [comment]
@rfjakob 

Thanks for the heads-up.  I will add HKDF and also Raw64 to cppcryptfs.

**Comment by bailey27** [comment]
I've added HKDF and Raw64 to cppcryptfs.
