### ISSUE TITLE
Occasional unclean dismount, but seems locked by cppcryptfs.exe itself, thx

### ISSUE THREAD

**Issue by ccchan234** [bailey27/cppcryptfs#165]
![Screenshot (691)_2](https://user-images.githubusercontent.com/37549409/174500173-a6e0784e-c3b4-49ae-b1c0-fc02c33ebb4f.png)

cppcryptfs ver: 1.4.3.12-64bit, win10pro, eng, 64bit

container is on Gdrive (Gdrive mounted as G:\)

the container is mounted at W:\

I always do these before unmount:
1. close all file explorer windows of any kind e.g. windows file explorer or xyplorer
2. in admin command prompt, do: net stop server (to disable windows cifs share)
 

sometimes it just cant clean unmount,
then I check with freeware lockhunter, and it give the information.

thanks

**Comment by bailey27** [comment]
Those open files look like special files created by Dokany.  I think there's no way to close them while the FS is mounted.

**Comment by ccchan234** [comment]
> Those open files look like special files created by Dokany. I think there's no way to close them while the FS is mounted.

err... i am going to unmount the file system and these files prevent a clean unmount, it's a mission impossible to clean unmount then?

anyway i use the lockhunter to kill the cppccryptfs.exe, then force dismount.

so far didn't notice data lost, yet.

thanks

**Comment by ccchan234** [comment]
hi, for the time being, cppcfs still dismount unclean, occasionally.
using lockhunter will always only list out cppcryptfs.exe itself.


today i run the lockhunter using admin mode,
and found that it will also list explorer.exe,
after killing the explorer.exe, cppcfs could dismount cleanly.

so... running lockhunt in admin mode helps.

thanks

**Comment by ccchan234** [comment]
hi,
recently i stopped using xyplorer,
and i almost never got such unlock problem so far.

so i suspect it's those 3rd party file manager cause the problem.
thanks
