### ISSUE TITLE
binary executable please

### ISSUE THREAD

**Issue by Kodiman** [bailey27/cppcryptfs#17]
Hi, Your cppcryptfs is excellent. Please do provide binary exe of the new version. Much appreciated. Thanks.

**Comment by sergeevabc** [comment]
Dear @bailey27,
Could you be so kind to generate ```.exe``` for the rest of us who are mere Windows users w/o compiler?

**Comment by sergeevabc** [comment]
Err… Hello?

**Comment by bailey27** [comment]
There is a binary release now.  I hope to release a signed executable in the near future.

**Comment by Kodiman** [comment]
hi. your software is excellent quality. much appreciated. thanks.

**Comment by sergeevabc** [comment]
Be sure to remember of https://github.com/bailey27/cppcryptfs/issues/18
