### ISSUE TITLE
Unauthorized Internet connection

### ISSUE THREAD

**Issue by sorcodiv** [bailey27/cppcryptfs#177]
Hello!
Firewall logs a connection attempt from cppcryptfs.exe and cppcryptfsctl.exe when I mount a volume with command like "cppcryptfsctl.exe --mount=c:\fs --drive=d --config=demo.conf --password=..." (only on mount, not on application start).
Port 80. Adresses example: 184.31.15.*/24, 104.84.152.*/24, ect. DNS requests: subca.ocsp-certum.com, crl.certum.pl, evcscasha2.ocsp-certum.com.
I think it can be some Windows checks in function like WinVerifyTrust (used in certutil.cpp)...
Can you check, what is the purpose of these connections and can it be disabled?
Version: 1.4.4.0-x64, sha256:
ec200456cee8a3572205ddc9d1c304e6bbe232b1bbad099175dae4034f332098  cppcryptfs.exe
f6f0fc14a2d8dcb4a7492438317b4f7327ae258127d6a7b2750546dcc06a9808  cppcryptfsctl.exe

**Comment by bailey27** [comment]
Those sha256's are what I have for 1.4.40 64-bit.

certum.pl is the provider of the code signing certificates.  The executables are signed by me and also by Encedo Limited with their extended validation certificate.  Both of us have certificates from certum.pl.  I don't know what ocsp-certum.com is.  I get nx domain when I try to look it up.  But certum.pl is the certificate provider.

In release versions, when you use cppcryptfsctl to control cppcryptfs, they both validate the signatures on each other and make sure they're signed by the same entity.  I'm pretty sure it just makes sure the first signatures match (Encedo's).  

I think the calls they make to validate the signatures are causing some Microsoft library code to make those internet connections.  Neither cppcryptfs nor cppcryptfsctl have any networking calls in them.  They talk to each other over a local named pipe.

**Comment by sorcodiv** [comment]
Thank you! I agree, it looks like some Microsoft library makes those internet connections. I think this issue may be closed.
