### ISSUE TITLE
Gocryptfs with scryptn >16 is not compatible

### ISSUE THREAD

**Issue by Davek145** [bailey27/cppcryptfs#179]
Cppcryptfs is currently unable to open any encrypted directory created in gocryptfs with -srcyptn >16. So with N parameter in gocryptfs.conf > 65536.
I believe that the issue is in cryptconfig.cpp, where SCRYPT_MB constant limits max memory for EVP_PBE_scrypt to 72MB. This max memory limitation needs to be increased to allow compliance with currently recommended security settings from OWASP:
https://cheatsheetseries.owasp.org/cheatsheets/Password_Storage_Cheat_Sheet.html#maximum-password-lengths

For current default of r=8 and p=1 recently updated recomentation is this:
N=2^17 (128 MiB), r=8 (1024 bytes), p=1

**Comment by bailey27** [comment]
I've made the memory limit for scrypt dynamic and based on N.

I've also added the ability to to specify N (actually specify log2(N) like gocryptfs) when creating a filesystem, changing the password, or recovering the filesystem.

Like gocryptfs, the range for scryptn is 10-28, but I can't get anything bigger than N = 2^20 to work in openssl (key derivation fails). I tried increasing my extra padding from 8MB to 128MB,but that didn't help.  N = 2^21,8,1 would require over 2GB.  

It should be released in a few days after a little more testing.

**Comment by Davek145** [comment]
Thanks, that is great and fast move. I agree with you that N > 20 is already very memory demanding. What I'm using is customized gocrypfs with increased P, so that I do not have to go so high with memory requirements while keeping same level of difficulty for attacker to brute force the scrypt password hash. Good think is that I need this customized gocryptfs only when creating the gocryptfs.conf or changing the password. For all other operations, both standard version of gocryptfs as well as cppcryptfs can work with gocryptfs.conf with P>1.
But still it is wise now to have N>16 and it is good that you made cppcryptfs compatible with what gocrypfs now does.

**Comment by bailey27** [comment]
1.4.4.1 is out with support for scryptn.
