### ISSUE TITLE
any tool to get back the filename from an encrypted file+filename, provided i got the .diriv file on hand?

### ISSUE THREAD

**Issue by ccchan234** [bailey27/cppcryptfs#187]
sorry to ask but i searched this webpage and asked AI,
but still found no such solution.

i guess the command line shd be able to help.

did i miss something? 
could someone simply point me to the document?

thank you.

**Comment by neiaberau** [comment]
as per
   https://github.com/bailey27/cppcryptfs#command-line-options

if the drive is mounted on Z, then you can list encrypted/unencrypted like this
  cppcryptfs.exe -lZ:\

to translate a single file: Aik2nPzD8PRpWsK9IV7CAw located at C:\_encrypted
  cppcryptfs.exe -MC:\_encrypted\Aik2nPzD8PRpWsK9IV7CAw
