### ISSUE TITLE
Add support for -config option in GoCryptFS

### ISSUE THREAD

**Issue by eugenesvk** [bailey27/cppcryptfs#20]
In GoCryptFS there is an option NOT to store config files in the cloud, but pass **gocryptfs.conf** as an option
>#### -config string
>Use specified config file instead of CIPHERDIR/gocryptfs.conf

As I understand it (please correct me if I'm wrong), it allows me to use an easier (more convenient) password without compromising in any way the cloud security:
a) guessing an easy password from having access to the encrypted key stored in the cloud in gocryptfs.conf file is easy
b) guessing an encrypted key from having access to just the encrypted files, but not the encrypted key (as the gocryptfs.conf is stored locally) is extremely hard and actually doesn't depend on the strength of the password.
This makes it a very useful feature as it's relatively easy to manually move the config file to different machines just once after folders are created and then use a more convenient password rather than store config files in the cloud, but have to use a much stronger password

Would you please add such an option in your GUI/CLI as well?

**Comment by bailey27** [comment]
Yes, as I understand it, if an attacker does not have access to the config file, then the strength of your password is irrelevant.  

The password is used to encrypt and decrypt the 256 bit random AES key that is generated when you create the filesystem.  This random key is encrypted using your password and stored in the config file.

I'll look into adding the -config option to both the command line options and the gui.

**Comment by eugenesvk** [comment]
Thanks a lot!
