### ISSUE TITLE
Folder as mount point (in Windows platform)

### ISSUE THREAD

**Issue by heX16** [bailey27/cppcryptfs#22]
It's possible?
[encfs4win ](https://github.com/jetwhiz/encfs4win)can do it. (command: "encfs.exe d:\Data_Crypt\ d:\Data\")

**Comment by bailey27** [comment]
It would be possible to support using an empty folder as a mount point.  Dokany supports this.

I think it would require mostly user interface changes.

**Comment by bailey27** [comment]
It's working.

There is one limitation though.  I currently can't allow mounting reverse-mode filesystems to an empty folder.  They have to be mounted to a drive letter.  Only forward (normal) mode filesystems can be mounted to a an empty folder.

The reason is that when you mount a filesystem to an empty folder, the filenames get converted to all uppercase most of the time.  I've debugged this some, and it appears that it is being done upstream of Dokany.  I don't know why this happens.

Reverse mode does not work in case-insensitive mode because the file names would all be lost if whatever was archiving the encrypted files didn't preserve the case of the file names.  If the case of the encrypted file names is changed, then they'll base64 decode to gibberish instead of to the encrypted filename data.

Is this limitation a problem for you?

I plan to make a new release in the next couple of days anyway, but I'd like to know if you or anyone else is unhappy with this limitation.  I could continue debugging and see if there is a solution.

**Comment by bailey27** [comment]
cppcryptfs 1.4.0.10 has been released https://github.com/bailey27/cppcryptfs/releases/tag/1.4.0.10

It allows mounting filesystems to empty NTFS folders in forward (normal) mode.

**Comment by heX16** [comment]
> The reason is that when you mount a filesystem to an empty folder, the filenames get converted to all uppercase most of the time. 
I found a description of this problem:
https://github.com/billziss-gh/winfsp/issues/36#issuecomment-276769826
This is problem on Windows. It is difficult to solve this problem.

Direct mode - this is more than enough. I think few people use the reversible mode.
Many thanks!

PS Sorry for my English.

**Comment by bailey27** [comment]
I want to point out that currently the empty folder mount point must be added in the UI (by right-clicking on the list of drive letters on the mount tab and doing "Add Mount Point") before it can be used, even if you are mounting  using the command line.   

In other words, I noticed that mounting using the command line fails unless that mount point has already been added in the UI. 

I'll fix this soon.

**Comment by heX16** [comment]
Not work.  =(

OS: Windows 7 x64. 
Cmd "ver": Microsoft Windows [Version 6.1.7601]
CryptFS version: 1.4.0.10

Crash immediately when mounting.

Text from standard error widows:
```
Сигнатура проблемы:
  Имя события проблемы:	APPCRASH
  Имя приложения:	cppcryptfs.exe
  Версия приложения:	1.4.0.10
  Отметка времени приложения:	5a7a1ffb
  Имя модуля с ошибкой:	dokan1.dll
  Версия модуля с ошибкой:	1.0.3.1000
  Отметка времени модуля с ошибкой:	58d51fd6
  Код исключения:	c0000005
  Смещение исключения:	0000000000005ff5
  Версия ОС:	6.1.7601.2.1.0.256.48
  Код языка:	1049
  Дополнительные сведения 1:	b6ea
  Дополнительные сведения 2:	b6ea7e4470cbbc5d6ca5c6f36ce59fcc
  Дополнительные сведения 3:	afd8
  Дополнительные сведения 4:	afd80e34777b6f7b81162f37d266ba33
```
![default](https://user-images.githubusercontent.com/3930496/36136270-a508d532-10a0-11e8-8503-f538c2153e77.png)

Folder "D:\heXor\Crypted" contain 2 file: gocryptfs.conf, gocryptfs.diriv.

Cmd "dir":
```
D:\heXor>dir
 Том в устройстве D не имеет метки.
 Серийный номер тома: 0453-A3F4

 Содержимое папки D:\heXor

13.02.2018  09:27    <DIR>          .
13.02.2018  09:27    <DIR>          ..
13.02.2018  09:27    <JUNCTION>     Crypt [\??\Volume{d6cc17c5-1736-4085-bce7-964f1e9f5de9}\]
13.02.2018  09:25    <DIR>          Crypted
...
```

**Comment by bailey27** [comment]
Thanks for reporting this.

The Windows dynamic linker complains with an error dialog if you run old cppcryptfs (1.4.0.7 or before) with new dokany (1.10.x) and refuses to let it run, but it doesn't complain if you run new cppcryptfs with old dokany (1.0.x), and cppcryptfs crashes  like you saw.

I'll put a in check  for the Dokany version to make sure it's 1.10 or greater.

**Comment by bailey27** [comment]
The 1.4.0.11 has been released.   It doesn't require the mount point folder to be pre-configured in the ui if you're mounting from the command line.  

It also checks the Dokany version to make sure it's compatible.

**Comment by schnappijedi** [comment]
If find a solution to mounting a reverse volume to an empty folder that would be great. See referenced issue with gocryptfs. Thanks for your work on cppcryptfs. First looked at when more than just binary and Dokany driver was required.

**Comment by bailey27** [comment]
The reason for not supporting mounting reverse mode filesystems to an empty folder is purely a Windows issue.  It isn't related to AES-SIV mode.

**Comment by schnappijedi** [comment]
Huge proponent of keeping code simple but originally thought a better option/ solution might be a "Syncthing" command line option on gocryptfs side to add a ".stfolder" to a read-only reverse volume. Hence the reference but have since changed mind.

**Comment by bailey27** [comment]
The restriction on using an empty NTFS directory as a mount point in reverse mode has been removed in cppcryptfs 1.4.0.19 

https://github.com/bailey27/cppcryptfs/releases
