### ISSUE TITLE
Is cppcryptfs compatible with gocryptfs?

### ISSUE THREAD

**Issue by NiceGuyIT** [bailey27/cppcryptfs#26]
The README.md states cppcryptfs is based on the design of gocryptfs but doesn't explicitly state whether cppcryptfs is compatible with gocryptfs. Can cppcryptfs open and use a gocryptfs container?

I have KeePassXC databases inside a gocryptfs container and sync across platforms using Syncthing. I use Linux on the desktop, macOS on the laptop and Windows in Virtualbox. Currently, I'm using Virtualbox's shared folders to access the hosts KeePassXC database but sometimes this isn't possible. Syncing the gocryptfs container to Windows and using cppcryptfs would fix this problem.

**Comment by bailey27** [comment]
@NiceGuyIT, cppcryptfs is compatible with gocryptfs. You can mount filesystems created with gocryptfs with cppcryptfs and vice versa.  I test only the defaults when make the fs with gocryptfs, so there may be some combination of filesystem creation options that won't work with cppcryptfs.

The readme says it is compatible, but that statement comes at the very end of the readme.  I will go put a statement about this near the top to make it easier to find.
