### ISSUE TITLE
Update for Dokany 1.2.0.1000

### ISSUE THREAD

**Issue by ScottRFrost** [bailey27/cppcryptfs#31]
I tried Dokany 1.2.0.1000 (which came out a week ago), and none of my drives will mount.  Please update cppcryptfs for 1.2.x since 1.2.x is now stable and the latest 1.1.x build is 8 months old.

https://github.com/dokan-dev/dokany/blob/master/CHANGELOG.md

**Comment by bailey27** [comment]
I built it against Dokany 1.2.0.1000.

The new version is 1.4.0.18 

https://github.com/bailey27/cppcryptfs/releases

It sounds like the Dokany team might have solved the problem that was preventing me from allowing emtpy NTFS directories to be used as mount points in reverse mode.  I'll investigate that when I have time.

**Comment by ScottRFrost** [comment]
Works great.  Thank you!

**Comment by heikoh81** [comment]
Thank you for updating & adapting cppcryptfs to the newest Dokany version!
