### ISSUE TITLE
possible to use in win"PE" say win7 recovery/install phase?

### ISSUE THREAD

**Issue by ccchan234** [bailey27/cppcryptfs#35]
Previously used truecrypt it allow us to
run truecrypt even in win7 recovery
environment.

it helps as some ghosting environment like
paragon hd manager are also "pe", and allow protection on system install file/driver.

just tried with cppcfs.
seems only 64bit.
and dokany 1.2 bundle.  the setup.exe nor
.msi dunt install in win"pe" so cpcfs dunt run.

any hope for this?

a problem with TC is that the volume size.is fixed,.so using cppcfs helps

thanks.

**Comment by bailey27** [comment]
cppcryptfs is a stand-alone, mostly statically-linked executable. It is possible to build a 32-bit version.

The only thing it depends on is Dokany.  So I think if Dokany could be made to work in the PE environment, then it should be possible for cppcryptfs to work in PE as well.
