### ISSUE TITLE
easy got "too long filename" for onedrive?

### ISSUE THREAD

**Issue by ccchan234** [bailey27/cppcryptfs#36]
hi~
i mostly use default settings of cppcryptfs.

seems onedrive have limit that total of (folder names i.e. path + file name) have a limit of 260?
(now 400?) 

this may easy done over by cppcryptfs and making them not very compatible?

thanks.

cppcryptfs seems ok with gdrive, opendrive thu.

ref:
may be limit is now 400, but seems still not enough for cppcryptfs? thx
The entire path, including the file name, must contain fewer than 400 characters for OneDrive, OneDrive for Business and SharePoint Online. If you exceed that limit, you'll receive an error message.
https://support.office.com/en-us/article/invalid-file-names-and-file-types-in-onedrive-onedrive-for-business-and-sharepoint-64883a5d-228e-48f5-b3d2-eb39e07630fa

**Comment by ccchan234** [comment]
I can use cppcryptfs and store my files primarily on google drive,

but when I copy (use rclone, which does not affect the copy) to onedrive,
it told the errors, and seems is the too long path/file name problem.

Any work around for this?

my current thinking is:

use some small tools that can detect very long file names/path in the unencrypted plain files, try to make them shorter, see if this will result in a shorter path in cppcryptfs.

tools like "TLPD" are foss and can do this.

thank you

**Comment by bailey27** [comment]
When a file name is encrypted, it is converted from UNICODE-16 to UTF-8 which, depending the language, might cause the number of characters to increase. Then it is encrypted, which causes it to be padded by up to 16 bytes. Then it is base64 encoded, which typically results in a 33% increase in length. The encrypted file names can therefore be significantly longer than the unencrypted names.

cppcryptfs overcomes the 255 character file/folder name limit by using the long-filename file to store the encrypted file/folder name.  So keeping individual file and folder names under 255 characters isn't a problem.

The problem is I think keeping the whole path (multiple folders plus file names) under 260 characters.  

The Windows NTFS filesystem has a limit of 32000 characters for paths.  I have no idea why OneDrive has such a small limit.

The only suggestion I have is to use uencrypted file names.

**Comment by ccchan234** [comment]
It seems dropbox, box along onedrive DO have path+filename length of around 260-400. (they claim that
windows only support up to 260 so more than that is meaningless.

So what could we do?

Just wanna ask 1 simple question:

Will it help if I rename my path+filename to be shorter?

If rename into shorter path+filename helps then I will simply use some tools, as I say above,
make sure in the unencrypted folders, the path are say < 150.

Then when encrypted, they are less likely to over 260-400.

Will this work?

thanks




> When a file name is encrypted, it is converted from UNICODE-16 to UTF-8 which, depending the language, might cause the number of characters to increase. Then it is encrypted, which causes it to be padded by up to 16 bytes. Then it is base64 encoded, which typically results in a 33% increase in length. The encrypted file names can therefore be significantly longer than the unencrypted names.
> 
> cppcryptfs overcomes the 255 character file/folder name limit by using the long-filename file to store the encrypted file/folder name. So keeping individual file and folder names under 255 characters isn't a problem.
> 
> The problem is I think keeping the whole path (multiple folders plus file names) under 260 characters.
> 
> The Windows NTFS filesystem has a limit of 32000 characters for paths. I have no idea why OneDrive has such a small limit.
> 
> The only suggestion I have is to use uencrypted file names.

**Comment by bailey27** [comment]
260 characters used to be the limit on Windows.  A lot off apps are hard-coded to expect paths to never be longer than this.   

If you make the unencrypted paths shorter, then the encrypted paths will be shorter as well.

**Comment by ccchan234** [comment]
Would like to express that cppcryptfs could easily have long file name problem in NTFS.
I use yyyymmdd-hhmmss as a stamp to organize things,
like 20181118-161927.
when the path have several of this, then it's going to be beyond the limit of cppcryptfs
and cause read/write error.

using unencrypted path name is not practical.

Wish there could be work around , thanks.

**Comment by ccchan234** [comment]
update:
could be the file manager's problem instead, thanks

**Comment by ccchan234** [comment]
Hi~
I do some research on this long file name limitation and at this moment 20181202-023945
found that:
path+file name limit is
google drive: 3xxxx character
onedrive 400
dropbox, box around 300-400.

I study this again becoz
files I stored on gdrive, when rclone to onedrive,
lot a lot of missing.

I think those will be lost due to too long file path+name.

At the moment, I have to use gdrive as my primary and secondary cloud storage.
Which is not too good as if gdrive fail for 1 account, the other could suffer and
thus the secondary storage should better be say onedrive/dropbox/box.

i read gocrypt's comparison chart,
cryptomator could "flatten folders and make long files names into 3xx characters".
But their dev is slow, and rclone mount + onedrive is NOT working with cryptomator (i reported to them).

so the situation is like this at the moment.

thanks

**Comment by elijahfrankinson** [comment]
Use LongPathTool it will solve your problem of deleting and copying long path files

**Comment by ccchan234** [comment]
hey,
my path have say 1000 character s that
are meaningful,

how can a software help?
which part it deletes?
every single character is meaningful
as i said, unless i change the naming practise.

what mechanism can help?

thanks.
