### ISSUE TITLE
Issue with mounted folders after shutdown

### ISSUE THREAD

**Issue by PieDelivery** [bailey27/cppcryptfs#37]
This is more of a QOL thing than a bug. I have a few filesystems mounted to some folders on C:. When I close the GUI, the folders unmount with no problem. When I shut down the computer, however, the folders unmount, but not completely. Upon restart, the mounted folders still act as mounted folders (the image looks like a shortcut still), but with no backend, and give an error when trying to open them. When trying to remount to these folders, the GUI states that they're not valid folders for mounting. The solution for me has just been to delete and remake these folders, and that works fine. I'm not sure if this is a bug with cppcryptfs or Dokany.

Appreciate the help, and thanks for the great software!

**Comment by bailey27** [comment]
Thanks for reporting this issue.

I was able to reproduce it.

I was able to fix it by hooking the WM_ENDSESSION message and unmounting all filesystems if the session is ending.

I'll make a new release soon.  I'm waiting on a new code signing certificate (the current one expires on Oct. 31) before making the release.  It should be some time this week or next weekend.

**Comment by PieDelivery** [comment]
Thanks for the quick work on this issue, I'll test the new release and report back!

**Comment by bailey27** [comment]
1.4.0.22 is out with this fix.   You can download it from here.

https://github.com/bailey27/cppcryptfs/releases

**Comment by PieDelivery** [comment]
Thanks for this, everything works as expected!
