### ISSUE TITLE
Cannot commit inside mounted volume

### ISSUE THREAD

**Issue by ray-mints** [bailey27/cppcryptfs#39]
Whenever I try to commit inside my mounted volume - I get an error message, which says 
`fatal: cannot update the ref 'HEAD': unable to append to './git/logs/HEAD': Bad file descriptor`

See a screenshot:
![selection_014](https://user-images.githubusercontent.com/22933252/47786025-1d455400-dd13-11e8-941a-6ed14f4c6685.png)

Currently I have to move my project to some unencrypted folder, commit and then move it back.

I am using Windows 7 Ultimate N x64 with Service Pack 1.

**Comment by bailey27** [comment]
Which git are you using?  Is it from MINGW?

I'm using git from the git website, and it works for me on a cppcryptfs volume.

https://git-scm.com/download/win

I just did a quick test (checked out my source tree and committed a change).  I normally use git on my C: drive.

**Comment by ray-mints** [comment]
This git is from official website and it is installed on C: drive.
I will try on a different computer later today.

**Comment by ray-mints** [comment]
![screenshot_1](https://user-images.githubusercontent.com/22933252/47896363-de7bdf00-de75-11e8-89ab-c9afef6a8bd1.png)
It actually worked on a different laptop. Weird it hasn't worked before. I'll keep testing later.
