### ISSUE TITLE
cppcryptfs should have more promotion. should enhance popularity

### ISSUE THREAD

**Issue by ccchan234** [bailey27/cppcryptfs#41]
i think somehow we should have something to try promote cppcryptfs.

may be we could make a slogan, and singature (for email/post) etc and 
let us users use in our daily email/forum usage to promote cppcryptfs? just like
the linux stickers.

-----------

I mostly use windows. 

I started using crypt0mat0r, b0xcrypt0r, then know from b0xcrypt0r (before ver 2.0) that itself is from encfs,
and then from encfs, i later found there is an updated one (by the maintainer of encfs) i.e. gocryptfs.
then now for windows I know there is cppcryptfs.

In this yr 2018 I tested both encfs4win and cppcryptfs. At first encfs4win is my choice as
I can use encdroid on android for the data too.
BUT encfs4win always cause BSOD when copying large files, boot problem etc in windows. 

So cppcryptfs is my only choice now, even thru I cant access the data on android.

cppcryptfs is, as the author say, robust enough.
Indeep these file layer method is more smart than truecrypt,
so I think cppcryptfs could substitue truecrypt/veracrypt (I am turning from TC/VC to cppcryptfs).

I am from hong kong,
yet I didn't heard of any other people use cppcryptfs, even it's ready in .exe made for windows
and is FOSS, i.e. could be trusted with source. and it's free.

we are pleased for the cppcryptfs. thanks the author.

**Comment by ccchan234** [comment]
thru I think posts like this may just disturb others but I do think cppcryptfs/gocryptfs need to get promoted.
It's not found in youtube. A larger user base definitely will help, even for FOSS.

Admin/Author pls close this post after disturbed you, thank you.

**Comment by bailey27** [comment]
Thanks for the encouragement!
