### ISSUE TITLE
Win10 1809: No auto-dismount on shutdown

### ISSUE THREAD

**Issue by heikoh81** [bailey27/cppcryptfs#43]
Hi,

since Win10 (LTSC 2018) ([Version 10.0.17763.165]), mounts are no longer automatically dismounted on windows shutdown. This is a freshly installed system. It worked on an older Win10 (LTSB 2016) version before. cppcryptfs = 1.4.0.22

I do a proper shutdown. Fast start is disabled!

I'd like to have cppcryptfs auto-dismount my mounts if I forget to do this manually.
Any suggestions? Maybe other checkbox option is needed?

Best regards,
Heiko

**Comment by bailey27** [comment]
I don't have Windows LTSC.  I have the standard desktop release. I will try to get LTSC installed in my VM and see if I can reproduce the problem.

**Comment by heikoh81** [comment]
I did some further web research and found that this migh not be a bug, but a feature introduced with 1709 (had 1607 before):
https://winaero.com/blog/disable-apps-auto-reopening-windows-10/

I now placed a shortcut on my desktop instead of using the start button:
shutdown -t 0
This so far has always closed all open programs including cppcryptfs!

So I think this issue can be closed!
