### ISSUE TITLE
don't work

### ISSUE THREAD

**Issue by Eternity512** [bailey27/cppcryptfs#45]
Mounting does not work! Attached gif animation and screenshot.

Mirror: 
https://i107.fastpic.ru/big/2019/0106/fd/_341a4f81309f452099c54ce70cfd06fd.gif
https://i107.fastpic.ru/big/2019/0106/9b/30ade0017324c55d8337397e6b6f879b.png

**Comment by Eternity512** [comment]
mount to folder works

**Comment by Eternity512** [comment]
Add the feature "Favorites" so that you can quickly mount

**Comment by bailey27** [comment]
Did you try mounting to a drive letter besides A:?

A: used to not work, but Dokany fixed it a while back.  It worked for me, so I enabled mounting to A:.

Please try mounting to some other drive letter.

I see there is a new Dokany release. I'm going to update to it and build a new cppcryptfs and make a new release.  I hope to do that today.

**Comment by Eternity512** [comment]
The screenshot shows which drives I was trying to connect to. Not one did not work.
https://i107.fastpic.ru/big/2019/0106/9b/30ade0017324c55d8337397e6b6f879b.png

Cryptomator program also uses dokan. It mounts without problems. I had the latest version of the Dokan Library 1.2.1.2000 Bundle installed. https://github.com/dokan-dev/dokany/releases

**Comment by bailey27** [comment]
I installed Dokany 1.2.1.2000 and cppcryptfs works for me just fine without recompilation.  According to the Dokany release notes, recompilation shouldn't be necessary.

I have no idea why you can't mount to a drive letter.

cppcryptfs doesn't have favorites, but it does remember the last several most recently used encrypted filesystem directories in the select directory dropdown list, and it does remember and automatically select which drive letter or mount point folder you used to mount it to last time.  So it it functions similar to a favorites.
