### ISSUE TITLE
Possible for a 32bit binary release next time? thx

### ISSUE THREAD

**Issue by ccchan234** [bailey27/cppcryptfs#47]
Hi~

I used 64bit .exe for desktop for about 1yr.
Now want to deploy onto windows 10 atom tablets.

My newest one is with atom Z8500, it use 64bit UEFI and 64bit windows 10,
so the official signed release works fine.

But I still got two tablet, they still working with atom Z3745 tablets,
these use 32bit UEFI and could ONLY install 32bit windows 10.
As far as I know, the UEFI bit is hard to modify, at least not happening for old tablets. 

So I would like to vote for a 32bit binary release if possible, thanks

**Comment by bailey27** [comment]
I made a 32-bit release. It's on the releases page. 

 I haven't tested it thoroughly.  I did run it on 32-bit Windows 10 on my little Atom PC and verify that it basically works.

**Comment by ccchan234** [comment]
got it.

really appreciate your help.

thank you.
