### ISSUE TITLE
cppcryptfs incompatibility with teracopy asynchronous file transfer

### ISSUE THREAD

**Issue by Alondites** [bailey27/cppcryptfs#49]
**Preconditions**

cppcryptfs 1.4.0.24
Windows 10 x64 17763
Teracopy 3.26 with option to 'disable asynchronous file transfer' unchecked (i.e. asynchronous file transfer enabled)

**Steps to reproduce**

Copy largish file (affected filesize seems to be greater than 1GB) from unencrypted filesystem to cppcryptfs vault
or
Read largish file from cppcryptfs vault to unencrypted filesystem

**Expected**

File transfer completed

**Actual**

Teracopy fails with unspecified error

**Comment by Alondites** [comment]
I did some more testing and Beyond Compare also failed with error 'call to OS function failed'

Can't reproduce on various Windows encfs implementations, so hope it's an easy fix!

**Comment by bailey27** [comment]
I can reproduce it.  I've started debugging it, and I'll keep trying to solve the issue.

**Comment by bailey27** [comment]
I've come up with a fix for the TerraCopy problem.  I hope it will fix the problem with BeyondCompare also.  I'm pretty sure it's the same problem.

I'll make a release with the fix after some more testing.  I hope to release it tomorrow.

**Comment by bailey27** [comment]
1.4.0.25 is on the releases page.  It has the fix for TeraCopy

**Comment by bailey27** [comment]
Please try Beyond Compare and let me know if the fix for TeraCopy solves that as well.

**Comment by Alondites** [comment]
Looks like this is working now with both Beyond Compare and Teracopy.

Thank you.

**Comment by ccchan234** [comment]
wow Thanks the author and OP and others.

I also use and reported difficulties using cppcryptfs + teracopy/beyond compare.

But I just cant sure what is the problem so didn't report with certainty. 

Thank you

**Comment by ccchan234** [comment]
i now use fastcopy,
it handles 5gb files without error like tc/bc.

go try it out. thx
