### ISSUE TITLE
Is cppcryptfs 1.4.0.24 compatible with Dokany 1.2.2.1000?

### ISSUE THREAD

**Issue by heikoh81** [bailey27/cppcryptfs#50]
Hi,

is cppcryptfs 1.4.0.24 compatible with Dokany 1.2.2.1000?
On cppcryptfs 1.4.0.24 release page, it states:
> This release was built using Dokany 1.2.1.2000.

Greetings,
Heiko

**Comment by bailey27** [comment]
I just tested 1.4.0.24 with Dokany 1.2.2.1000 It passes all 500 tests in winfstest, and I tried a few manual tests and everything seems fine.

Dokany intends to maintain compatibility between minor version changes. They state that 1.2.2.1000 is a minor version.

So the answer is YES.

**Comment by heikoh81** [comment]
Thank you for the test!
