### ISSUE TITLE
Feature request: open new Explorer window upon mount

### ISSUE THREAD

**Issue by quiesces** [bailey27/cppcryptfs#52]
A new explorer window of the drive should open upon being mounted. Alternatively, open Explorer window for the drive upon double-clicking the path/mount letter in the drive list. This is a standard feature of drive mounting software, and really helps when working with multiple containers.

Other than this one missing feature cpp has been 100% for me. Thank you for all your work! It's awesome. Tens of thousands of files in thousands of complex sub-directories synced successfully and safely :)

**Comment by bailey27** [comment]
Thanks for the suggestion.

I've released 1.4.0.25, and it opens Explorer if you double-click.
