### ISSUE TITLE
some action on folders using UNC path cause cppcryptfs.exe to halt

### ISSUE THREAD

**Issue by ccchan234** [bailey27/cppcryptfs#53]
hi~

I mounted a cppcryptfs container to w:
then share w: as \\server001\cell000

when accessing \\server001\cell000 using windows explorer,
it's OK to open files,
but if add new folder, then change folder's name,
move files etc.

the cppcryptfs.exe will close itself.

Thank you.

cppcryptfs ver: 1.4.0.25
win7 pro 64b english 

easily reproducible for me.

**Comment by crazzyyfool** [comment]
Hi, is this issue limited to locations using UNC paths? 

I am having problems with write access to a mounted volume(s) as `"A:\"` with the encrypted data being a Dropbox folder located at `"C:\Users\orcha\Dropbox (Personal)\goVaults".` 

I can read all the unencrypted data as normal and there is no problems with encrypted data on Dropbox. I just can't seem to add any new files, folders, rename existing data etc - or any write acces - cppcryptfs crashes, then restarts promting me enter my details to mount an encrypted volume. The unencrypted volumes are not mounted as read-only. If I create a new empty encrypted volume in cppcryptfs, this seems to work OK, having both read/write access. 

I've tried elevated priviledges forboth cppcryptfs and Dropbox but neither attempt works. Uninstalling/re-installing cppcryptfs, Dokany, Dropbox etc also doesn't work. Everything worked as normal a few days ago. 

There is a possibility that as I'm a Windows Insider in the Fast Ring, the recent update to Windows 10 Insider Preview Build 18885 which is part of Skip Ahead (20H1) may be the problem. Though I'm sure things worked OK with the previous build 18875 (also 20H1) worked and prior to that build 18362 (which is part of 19H1) definately worked. 

I don't have another Windows system to test at the moment - though I could try in a VM. Incidently, if I mount the same encrypted Dropbox folder under Linux (Kubuntu 18.10/19.04) using Sirikali, I don't seem to have any issues. There are slight discrepancies with the version # of gocryptfs itself between each system - I'm not sure what verison cppcryptfs uses or whether this would be a problem anyway. 

Hope you can help with problem.

**Comment by ccchan234** [comment]
hi.

i updated to the most current version of cppcryptfs,
1.4.3.12, the dokany is v2 something.

now, for my google g suit account at G:\
i can share the G:\ as \\localhost\gdrive

then mount a container from that,
AND THEN share it as \\localhost\gdrive-cppcfs01

(this was not possible when I write my first post).

in this way, all files could be reached by the UNC path. and easier to be managed for me.

thanks and i'll close this issue.
