### ISSUE TITLE
winfstest failure in admininstrator process

### ISSUE THREAD

**Issue by alenas** [bailey27/cppcryptfs#55]
Hi,

Seems like winfstest (the latest version from Liryna) is failing when run as administrator.
If running as a normal user, then tests run as expected and fail only after 10th test.
Is that regression in admin mode, or that's the way it should be?

\t\base\10_GetSetSecurity.t
not ok 1 - expect "CreateFile S:\fc9e9153 GENERIC_WRITE 0 D:P(A;;GA;;;WD) CREATE_NEW FILE_ATTRIBUTE_NORMAL 0" 0 - got ERROR_INVALID_OWNER
not ok 2 - expect "GetFileSecurity S:\fc9e9153 DACL_SECURITY_INFORMATION" 0 - got ERROR_FILE_NOT_FOUND
not ok 3 - expect "SetFileSecurity S:\fc9e9153 DACL_SECURITY_INFORMATION D:P(A;;GA;;;WD)(A;;GR;;;SY)" 0 - got ERROR_FILE_NOT_FOUND
not ok 4 - expect "GetFileSecurity S:\fc9e9153 DACL_SECURITY_INFORMATION" 0 - got ERROR_FILE_NOT_FOUND
not ok 5 - expect "DeleteFile S:\fc9e9153" 0 - got ERROR_FILE_NOT_FOUND
not ok 6 - expect "CreateFile S:\fc9e9153 GENERIC_WRITE 0 D:P(A;;GA;;;WD) CREATE_NEW FILE_ATTRIBUTE_NORMAL 0" 0 - got ERROR_INVALID_OWNER
not ok 7 - expect "CreateFile S:\fc9e9153 GENERIC_READ 0 0 OPEN_EXISTING 0 0" 0 - got ERROR_FILE_NOT_FOUND
not ok 8 - expect "SetFileSecurity S:\fc9e9153 DACL_SECURITY_INFORMATION D:P(D;;GR;;;WD)" 0 - got ERROR_FILE_NOT_FOUND
not ok 9 - expect "CreateFile S:\fc9e9153 GENERIC_READ 0 0 OPEN_EXISTING 0 0" ERROR_ACCESS_DENIED - got ERROR_FILE_NOT_FOUND
not ok 10 - expect "SetFileSecurity S:\fc9e9153 DACL_SECURITY_INFORMATION D:P(A;;GA;;;WD)" 0 - got ERROR_FILE_NOT_FOUND
not ok 11 - expect "DeleteFile S:\fc9e9153" 0 - got ERROR_FILE_NOT_FOUND
not ok 12 - expect "CreateDirectory S:\c0a709f9 D:P(A;;GA;;;WD)" 0 - got ERROR_INVALID_OWNER
not ok 13 - expect "GetFileSecurity S:\c0a709f9 DACL_SECURITY_INFORMATION" 0 - got ERROR_FILE_NOT_FOUND
not ok 14 - expect "SetFileSecurity S:\c0a709f9 DACL_SECURITY_INFORMATION D:P(A;;GA;;;WD)(A;;GR;;;SY)" 0 - got ERROR_FILE_NOT_FOUND
not ok 15 - expect "GetFileSecurity S:\c0a709f9 DACL_SECURITY_INFORMATION" 0 - got ERROR_FILE_NOT_FOUND
not ok 16 - expect "RemoveDirectory S:\c0a709f9" 0 - got ERROR_FILE_NOT_FOUND
not ok 16/16

**Comment by bailey27** [comment]
Hi.  I'm sorry, but I can't reproduce the problem.  

I did a fresh clone (checkout) of Lyrina's winfstest and built a 64-bit release binary.

When I run it with cppcryptfs running as administrator, it passes 506/506 tests, and with cppcryptfs running not as administrator, it passes 500/506.

Administrator:

```
C:\git\lyrina\winfstest\TestSuite>run-winfstest.bat  . k:\
C:\git\lyrina\winfstest\TestSuite\\.\t\base\00_CreateFile_Dispositions.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\01_CreateFile_Attributes.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\02_CreateRemoveDirectory.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\03_FindFiles.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\04_MoveFile.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\05_CreateFile_Truncation.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\06_FileTimes.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\07_SetGetFileAttributes.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\08_CreateFile_Delete.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\09_CreateFile_Sharing.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\10_GetSetSecurity.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\streams\00_Create_Delete_FileStreams.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\streams\01_Create_Delete_DirectoryStreams.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\streams\02_FindStreams.t  ok

total ................................. ok 506/506

```
Not as Administrator
```
C:\git\lyrina\winfstest\TestSuite>run-winfstest.bat  . k:\
C:\git\lyrina\winfstest\TestSuite\\.\t\base\00_CreateFile_Dispositions.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\01_CreateFile_Attributes.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\02_CreateRemoveDirectory.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\03_FindFiles.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\04_MoveFile.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\05_CreateFile_Truncation.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\06_FileTimes.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\07_SetGetFileAttributes.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\08_CreateFile_Delete.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\09_CreateFile_Sharing.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\base\10_GetSetSecurity.t
not ok 10 - expect "DeleteFile k:\293625df" 0 - got ERROR_ACCESS_DENIED
not ok 11 - expect "CreateDirectory k:\293625df D:P(A;;GA;;;WD)" 0 - got ERROR_ALREADY_EXISTS
not ok 12 - expect "GetFileSecurity k:\293625df DACL_SECURITY_INFORMATION" 0 - got ERROR_ACCESS_DENIED
not ok 13 - expect "SetFileSecurity k:\293625df DACL_SECURITY_INFORMATION D:P(A;;GA;;;WD)(A;;GR;;;SY)" 0 - got ERROR_ACCESS_DENIED
not ok 14 - expect "GetFileSecurity k:\293625df DACL_SECURITY_INFORMATION" 0 - got ERROR_ACCESS_DENIED
not ok 15 - expect "RemoveDirectory k:\293625df" 0 - got ERROR_DIRECTORY
not ok 6/15
C:\git\lyrina\winfstest\TestSuite\\.\t\streams\00_Create_Delete_FileStreams.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\streams\01_Create_Delete_DirectoryStreams.t  ok
C:\git\lyrina\winfstest\TestSuite\\.\t\streams\02_FindStreams.t  ok

total ................................. ok 500/506 - not ok 6/506

```

**Comment by alenas** [comment]
My bad. I set up test incorrectly. I was running cppcryptfs as normal user, and then was running test as administrator. Did a rerun and everything is 100%.
