### ISSUE TITLE
cppcryptfs' GUI seems to not accept all characters in passwords

### ISSUE THREAD

**Issue by Freeedim** [bailey27/cppcryptfs#57]
Hi and thanks for cryptfs, which I like a lot

I ran into a minor issue lately. I usually create complicated passwords with weird characters taken in the vast UTF-8 space. Most of the time, whatever weird characters I can have pose no problem. Recently, I tried this password:
Æ¾eåĄ×Ð®ĦƔȸɲȄʔ˥ϾϠѾӺՅԕհᶔắ‡₷₰₯₠

I could create the encrypted folder without problem, but while trying to mount it (through the GUI), I had a popup error message saying "wrong password" (and yes, of course, it was copy pasted, so no error on that side).

In case you want to investigate this, here are the comma separated UNICODE code of those characters (as returned by the UNICODE() function in Excel 2019):
198, 190, 101, 229, 260, 215, 208, 174, 294, 404, 568, 626, 516, 660, 741, 1022, 992, 1150, 1274, 1349, 1301, 1392, 7572, 7855, 8225, 8375, 8368, 8367, 8352

**Comment by bailey27** [comment]
cppcryptfs uses a special edit control for entering passwords.

This control tries to make it harder for some other program running on your computer to get at the password as it is being typed into the password fields.

I didn't write this class.  It's open source by the creator of KeepPass.

The password field class treats character "×" as special.  This character looks like a small x, but not the same.  It's unicode 215 which is 0xd7 in hex.  

The result is you cannot use that character in a password.  Your password has that character.

I replaced the "×" in your password with an ascii small x, and it worked for me.  The other characters are ok to use.

I could change the special character to be something else, but then that could keep somebody who's using that new special character from mounting their filesystem, though I think it would be unlikely to happen.

**Comment by Freeedim** [comment]
Thanks you for your quick and very clear answer. Maybe it would deserve to be documented somewhere, although I understand nobody likes long documentations with hundreds of small technical details that are hardly ever useful...

**Comment by bailey27** [comment]
I documented it for the next release.
