### ISSUE TITLE
Exit code (ERRORLEVEL) not set

### ISSUE THREAD

**Issue by tigmac** [bailey27/cppcryptfs#60]
It seems that cppcryptfs does not set exit code, or at least in certain cases, thus it is not possible to capture error when mounting/unmounting programmatically from a script.

Also, command line execution is not synchronous - it does not wait for running instance to process the command, so that it may return to caller before e.g. drive is mounted.

These are vital features for reverse mode encryption which is typically used for scheduled automated backups.

**Comment by bailey27** [comment]
You can make it wait for the already running instance to process the command by using start /wait, e.g.

```

start /wait cppcryptfs -m c:\tmp\test -d k -p k

```

The other problems all come from the fact that cppcryptfs is a Windows gui app.  Setting ERRORLEVEL from an exiting Windows gui app appears to be very hard to do, if it is possible at all.  It's trivial to set it from a console app.

I wanted to make it so you could do everything from one executable.  When you run the second instance from the command line, it sends a message to the already running instance to execute what you specified.  The already running instance writes its output to the console of the parent process of the instance that you ran on the command line.

A big annoyance from this is that you can't redirect the output to a file or a pipe. 

I think the best way to solve the ERRORLEVEL and output redirection issues would be to make a console mode companion program (e.g. cppcryptfsctl.exe)  and have it communicate with the running instance via a remote procedure call mechanism.

**Comment by bailey27** [comment]
Does cppcryptfsctl solve this for you?

**Comment by bailey27** [comment]
cppcryptfsctl sets errorlevel
