### ISSUE TITLE
Suggest Fastcopy  over teracopy for use with cppcryptfs and google file stream

### ISSUE THREAD

**Issue by ccchan234** [bailey27/cppcryptfs#61]
Hi~

I previously wanna move all my movies into google file stream,
encrypt with cppcryptfs and watch back on the fly.

But with files > 4GB, teracopy reported error in most cases.
Other users also reported error on using cppcfs with teracopy or beyond compare.
(short: files > 4GB wont work if use teracopy/beyond compare)

I found fastcopy DO NOT report such errors,
and I am now using fastcopy for that purpose routinely,
with many files > 4GB.
NO single error is found.

So I will suggest fastcopy for that purpose.

This is a suggestion so I will close the issue next time I login later,
or the author could help to do that.

Thanks.

Thank you author for cppcryptfs.

**Comment by Nodens-** [comment]
@ccchan234 I would like to kindly remind you that this is an issue tracker not a forum. Posts should contain bug reports with reproduction directions and logs/screenshots or feature, documentation etc requests.

**Comment by ccchan234** [comment]
yeah but honestly gocryptfs and cppcrypts dont promote outside. i hardly can tell others this solution.

so i used to open an issue and then close it.

keeping that useful info only to myself i think is inappropriate.

and after i close the issue you please tell me how you can inform me.......

there need to be a way to communicate among the author and the users... already rare in number.
