### ISSUE TITLE
[Feature request] automatically delete desktop.ini just before deleting a folder (thus preventing the failure)

### ISSUE THREAD

**Issue by Freeedim** [bailey27/cppcryptfs#62]
Hi, and thanks for this great app!

I use cppcryptfs with Google Drive and Google "Backup & Sync".

Whatever settings I set in their app (with or without emblems on shared folders icons, with or without warning when deleting a shared resource), Google would create a hidden desktop.ini file in any newly created sub-folder of the main Google Drive folder.

Thus when I try to delete a folder from the "clear" mounted side, cppcryptfs first deletes all the encrypted files from the encrypted folder to be subsequently deleted, and tries to delete the encrypted folder. Which always fails since the desktop.ini file was not deleted.

Is there a way to automatically delete desktop.ini (or force the folder deletion even though it is not empty)?

Thank you for your attention.

**Comment by bailey27** [comment]
Hi.  It shouldn't be that hard to do.  I'll try to add this as a setting in the next release.

**Comment by bailey27** [comment]
I can't make my Google Drive with Backup  and Sync create the desktop.ini files.

I implemented the setting anyway, and tested it by making my own hidden desktop.ini files in the encrypted (real) directory structure.

Please try release 1.4.0.26 https://github.com/bailey27/cppcryptfs/releases.

If it doesn't work, then please either re-open this issue or create a new one.

**Comment by Freeedim** [comment]
Hi!

Many thanks for your quick and effective response. It works perfectly!

Maybe I should have specified that all of my Google Drive folders are shared with other people (through Google Drive, not through Windows/SMB...); I think this is the reason why Google Backup & Sync creates those desktop.ini files which contain the path to the "Shared" emblem to be applied on the folder icon.

Best!
