### ISSUE TITLE
Version to support Dokany 1.3.x

### ISSUE THREAD

**Issue by ScottRFrost** [bailey27/cppcryptfs#66]
1.3.0.1000 is out at https://github.com/dokan-dev/dokany/releases , with a few new features https://github.com/dokan-dev/dokany/blob/master/CHANGELOG.md

It's not clear if the current version is compatible with 1.3.x, so I'm still on the 1.2.x dokany for now.

**Comment by bailey27** [comment]
I just now released 1.4.0.27 which I built and tested with Dokany 1.3.0.1000

https://github.com/bailey27/cppcryptfs/releases
