### ISSUE TITLE
Problem with wildcard copy

### ISSUE THREAD

**Issue by formicine** [bailey27/cppcryptfs#71]
Hi, 
I have a problem copying files using wildcards in a cppcryptfs volume with file name encryption.

= ENVIRONMENT =
Microsoft Windows [Version 10.0.18362.418]
cppcryptfs 1.4.0.27  (md5sum = c9b1a037153094274bbe714d3c663409)
dokany 1.3.0.1000
dokanctl : Jul 24 2019 14:10:25
Dokan version : 130
Dokan driver version : 0x190

= STEPS TO REPRODUCE =
md test1
cd test1
echo Hello World>hello.txt
cd ..
md test2
cd test2
dir ..\test1\h*
copy ..\test1\h*

= EXPECTED RESULT =
hello.txt should be copied from test1 to test2

= FAILED RESULT = 
Running the "steps to reproduce" on a cppcryptfs volume with file name encryption:
> U:\\>md test1
> 
> U:\\>cd test1
> 
> U:\test1>echo Hello World 1>hello.txt
> 
> U:\test1>cd ..
> 
> U:\\>md test2
> 
> U:\\>cd test2
> 
> U:\test2>dir ..\test1\h*
>  Volume in drive U has no label.
>  Volume Serial Number is 9881-D2D2
> 
>  Directory of U:\test1
> 
> 11-Oct-19  13:17                13 hello.txt
>                1 File(s)             13 bytes
>                0 Dir(s)  456,402,718,720 bytes free
> 
> U:\test2>copy ..\test1\h*
> **The system cannot find the file specified.**

Running the "steps to reproduce" on a windows volume (C:), or a cppcryptfs volume without file name encryption:
> V:\\>md test1
> 
> V:\\>cd test1
> 
> V:\test1>echo Hello World 1>hello.txt
> 
> V:\test1>cd ..
> 
> V:\\>md test2
> 
> V:\\>cd test2
> 
> V:\test2>dir ..\test1\h*
>  Volume in drive V has no label.
>  Volume Serial Number is 73BD-4717
> 
>  Directory of V:\test1
> 
> 11-Oct-19  13:26                13 hello.txt
>                1 File(s)             13 bytes
>                0 Dir(s)  456,393,940,992 bytes free
> 
> V:\test2>copy ..\test1\h*
> **..\test1\hello.txt
>         1 file(s) copied.**

This is the configuration for the U: volume in the previous test (with file name encryption)
> {
> 	"Creator": "cppcryptfs v1.4.0.27",
> 	"EncryptedKey": "(... deleted ...)",
> 	"ScryptObject": {
> 		"Salt": "(... deleted ...)",
> 		"N": 65536,
> 		"R": 8,
> 		"P": 1,
> 		"KeyLen": 32
> 	},
> 	"Version": 2,
> 	"VolumeName": "",
> 	"FsFeatureDisableMask": "00000",
> 	"FeatureFlags": [
> 		"EMENames",
> 		"LongNames",
> 		"DirIV",
> 		"HKDF",
> 		"Raw64",
> 		"GCMIV128"
> 	]
> }

And for the V: volume (without file name encryption)
 > {
> 	"Creator": "cppcryptfs v1.4.0.27",
> 	"EncryptedKey": "(... deleted ...)",
> 	"ScryptObject": {
> 		"Salt": "(... deleted ...)",
> 		"N": 65536,
> 		"R": 8,
> 		"P": 1,
> 		"KeyLen": 32
> 	},
> 	"Version": 2,
> 	"VolumeName": "",
> 	"FsFeatureDisableMask": "00000",
> 	"FeatureFlags": [
> 		"PlaintextNames",
> 		"HKDF",
> 		"Raw64",
> 		"GCMIV128"
> 	]
> }

I have attached son procmon dumps isolating "dir ..\test1\h*" 
[logfiles.zip](https://github.com/bailey27/cppcryptfs/files/3719223/logfiles.zip)

If you compare the log for U: (encrypted file names) and V: (unencrypted file names), they are almost identical, but for some CreateFile operations U: reports "NAME NOT FOUND" and V: reports "NAME INVALID". I don't know if this is significative.

**Comment by bailey27** [comment]
Thanks for reporting this.

I use TCC LE x64 14.0 for my command line shell, and it works.

But I can reproduce it with the standard CMD shell.

I'll try to debug it this weekend.

**Comment by bailey27** [comment]
I found the bug and fixed it.

What's happening is Windows is giving cppcryptfs the filename "\test1\h*" and  asking cppcyryptfs to open an existing file with that name.  Windows is expecting cppcryptfs to return the NTSTATUS version of ERROR_INVALID_NAME.   But cppcryptfs encrypts the filename, tries to open it, and returns (the NTSTATUS version of) ERROR_FILE_NOT_FOUND.

This throws Windows off, and it doesn't continue to copy the file.

So now if the filename contains a wildcard (* or ?), I return the NTSTATUS version of ERROR_INVALID_NAME, and it works.

I hope to upload a release with this fix later today or tomorrow.

**Comment by bailey27** [comment]
I uploaded 1.4.0.28 with the fix for the problem https://github.com/bailey27/cppcryptfs/releases.
