### ISSUE TITLE
Backing up .diriv files and the .conf

### ISSUE THREAD

**Issue by quiesces** [bailey27/cppcryptfs#73]
I am using cppcryptfs with Google File Stream.

While almost any cloud provider has versioning, it feels like backing these vital files up an additional time would be smart in case of a catastrophic failure. I believe this robocopy would do the trick:

`ROBOCOPY C:\Unencrypted_Source D:\Backup_Destination *.diriv /E`
`ROBOCOPY C:\Unencrypted_Source\gocryptfs.conf D:\Backup_Destination\gocryptfs.conf /E`

But I'm hesitant to run it on my own drive. Is there another known or established backup procedure that's been used? And relatedly, is it wise to print out the .conf file? An in-software prompt to do so may be helpful, since the entire file system relies on this one file.

These are 2 small details that feed into good practices with using the software, which I've found to be 100% rock solid! Thanks for all your work on this Bailey.

**Comment by bailey27** [comment]
The main thing is to not forget the password or accidentally delete gocryptfs.conf.  All the password does is decrypt the actual encryption key in gocryptfs.conf.

Printing the conf file is not going to help if you forget the password.

I would make several digital backup copies of the conf file and write your password down on paper and keep it in a safe place.

The diriv files are needed for decrypting the file names in their respective directories, but not the actual data.  I think they are of lesser importance.

I periodically make an encrypted backup of everything in my encrypted fs (of the unencrypted data).

I use gnu tar and gpg from the cygwin distribution from Red Hat.  cygwin is free and provides many Linux utilities for Windows.

I make a tar archive of all my unencrypted files and pipe it though gpg using AES-256 symmetric encryption (AES is not the default with gpg, CAST-5 is).  gpg compresses by default before it encrypts.

This way, even if both cppcryptfs and gocryptfs stop working, I could still get my data back.

A good thing about reading all the unencrypted data is this causes cppcryptfs to verify the integrity of all the files.   If a file were corrupted,  then cppcryptfs would report an error to tar which would print a message in the console window.

This does have the disadvantage of having to pass all my unencrypted data through memory, but I think its worth it for the integrity check and for having a backup that depends only on very common open source software (tar and gpg).

**Comment by quiesces** [comment]
Thank you for this write-up and for addressing all the ideas about integrity and concerns I had. You've put a huge amount of care into the project and it shows. Thanks again bro.
