### ISSUE TITLE
Long path length

### ISSUE THREAD

**Issue by tc234** [bailey27/cppcryptfs#76]
- OS Win 8.1 & Win 10 with long path enabled
- cppcryptfs 1.4.0.27 x64.exe &cppcryptfs 1.4.0.28 x64.exe
- Dokan_x64 1.3.0.1000
- Cloud cliennt https://disk-o.cloud/en (mail.ru based cloud)
- doublecmd for file management to avoid 260 char limitation

Tested configurations
1. I can create long paths, using locally hosted cppcryptfs   .
2. I can create long paths using unencrypted disk-o .
3. I cannot create a path longer than 160 char (~ 260 char encrypted) fro cloud hosted files. Looks like path length problem.
4. I created a long path cppcryptfs  locally and copied it into the cloud. I can browse it but I cannot do any files operations for long paths.

Any ideas how to tackle this issue?

**Comment by pythonInRelay** [comment]
It's most likely a limitation with your cloud provider. Check the 'rclone' documentation and see if your provider is listed there. In that specific page it'll tell you the max character/path length info for that provider. Most are 255 char.

**Comment by tc234** [comment]
I think there is something with file system driver/pipe  (?) no sure about proper terminology. 

My oversimplified understanding of tested options. ( tested in both Win 10 and Win 8)

1. files -> cloud client ->  success over 255 char
2. files -> cppcryptfs  -> mono -> local drive -> success over 255 char
Combining options above
3. files -> cppcryptfs  -> mono -> cloud client -> ?   breaks for ~ 170 chars ( around 255 encrypted)

Each arrow (->) has some limitations but each arrow separately works fine together but options 3 fails.

**Comment by pythonInRelay** [comment]
I'll say again. I am very sure that 255 char is the limit of your cloud provider bar none.

Try using the short names option and see if the error persists.
