### ISSUE TITLE
having trouble mounting reverse mode in command line

### ISSUE THREAD

**Issue by otterpro** [bailey27/cppcryptfs#77]
I have created a reverse mode and it mounts the disk in reverse mode with GUI.  However, when I use the command line to mount reverse mode, I always get this error message "wincppcryptfs: the mount point directory does not exist".

As an example, unencrypted files are in `q:\1\` directory and the reverse mode should be mounted to `r:\`.  I've verified that .gocryptfs.reverse.conf exist.  Again, it mounts fine with GUI, but I need to automount it 
In command line, I've tried this:

    cppcryptfs --reverse --mount=q:\1\ -p=<mypassword> --drive=r:\ --tray --exit
* I've also tried creating and mounting other reverse mounts, but I am getting the same result.
* I'm using latest cppcryptfs v1.4.0.28 and dokany 1.3.0.  
* Is there another way to mount it automatically, perhaps using the GUI, as a workaround? 
* Or did I forget something in the command line parameter?

**Comment by bailey27** [comment]
Hi.  There are two things you need to change about your command line to make it work.

First, there can't be an = after the -p.  If you use the short form of the the command line options, then you need to have the option argument come right after the the option switch (with no space).

The second problem is that my code is interpreting the "r:\" in --drive=r:\ as a directory that doesn't exist.  You need to use --drive=r:  or --drive=r if you want to mount to drive letter R.

Here is an example that works for me.  I don't have a q: drive so I used d:.  In this example, the password is "ABC123" 

cppcryptfs --reverse --mount=d:\1\ -pABC123 --drive=r --tray --exit

I apologize for the confusion, and I intend to improve the documentation.

**Comment by bailey27** [comment]
I've added to the documentation.
