### ISSUE TITLE
Binary releases soon?

### ISSUE THREAD

**Issue by jkaberg** [bailey27/cppcryptfs#8]
It's been a while. How about some binary releases? Release them under alpha tag or something, so people know what to expect :-)

**Comment by bailey27** [comment]
@jkaberg ,

I think cppcryptfs is reasonably solid.  But I haven't had much feedback.  The only person I know who is (or was) using it besides myself is the guy who asked me to add the command line options (which I did).

So all I really know is that it works for me, and it passes winfstest.

Are you using it?

**Comment by jkaberg** [comment]
I'm not using it, yet. I tried compiling but I had issues with OpenSSL (and something more, can't remember) and pretty much gave up :-)

**Comment by bailey27** [comment]
@jkaberg ,

Did you see my build instructions?  I put them up about two months ago.  I'm not sure if they were there when you tried to build it before.

https://github.com/bailey27/cppcryptfs/blob/master/INSTALL.md

**Comment by jp341** [comment]
I would be very interested in testing out a binary release, would even be fine with you emailing it to me if you don't want to post a binary on here.  Am afraid I don't own Visual Studio Pro.
I'm looking for an alternative to Boxcryptor Classic, which is no longer updated and has a bug that freezes explorer in CBFS.  I've tried basically everything out there, the cloest stable solution being EncFSMP but it is slow and especially for lots of small files, it uses Pismo File Mount.  Boxcryptor classic blows everything away in terms of performance, but the intermittant explorer freezes (requiring a restart!) make it untenable.

**Comment by bailey27** [comment]
You can build cppcryptfs with Visual Studio 2015 Community edition, which is free.

https://www.visualstudio.com/vs/community/

There are detailed build instructions in https://github.com/bailey27/cppcryptfs/blob/master/INSTALL.md

**Comment by jp341** [comment]
Thanks, I misunderstood the FAQ where you state professional edition is required for MFC.  
I was able to compile properly and am testing it now.  

A couple of things to add to the build instructions.  OpenSSL build failed on missing nasm, so I installed nasm manually and added the bin directory to the path.  Then all your instructions worked without issue.
Also, I installed git from VS install rather than via cygwin.

Many thanks, I will post some benchmarks comparing Boxcryptor Classic, EncFSMP and cppcryptfs soon.

**Comment by bailey27** [comment]
That's great.  Thanks for taking the time.  

I already had nasm installed, and I forgot that it was a requirement.

Did you need to use those extra set commands I listed in Install.md?

```
So these "set" commands probably won't be needed, but here they are just in case.

set include=C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\um;%include%
set include=C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\shared;%include%
set include=C:\Program Files (x86)\Windows Kits\10\Include\10.0.10586.0\ucrt;%include%

set lib=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10586.0\um\x64;%lib%
set lib=C:\Program Files (x86)\Windows Kits\10\Lib\10.0.10586.0\ucrt\x64;%lib%

```

**Comment by jp341** [comment]
No, didn't need to use those.  I was pleasantly surprised how easy it was, you did a great job with instructions.

**Comment by bailey27** [comment]
Thanks.  I've added a note about nasm in INSTALL.md.

**Comment by jtrumble** [comment]
Binary releases would be nice. I've been using this for about 3 - 4 months now (also found the build instructions very well laid out) and I haven't had any outstanding issues, thanks for the work you are putting in Bailey! I wouldn't have been able to use this without your port.

**Comment by blahjig** [comment]
Here is a copy I compiled with the current source code today:
[cppcryptfs.exe.txt](https://github.com/bailey27/cppcryptfs/files/776713/cppcryptfs.exe.txt)

**Comment by Kodiman** [comment]
hi, cppcryptfs is excellent. please compile and post newest version binaries. thanks

**Comment by Kodiman** [comment]
Hi, BLAHJIG, Please do us the favor of posting current version build of cppcryptfs.exe. As you did above. Thanks for your help. Much appreciated. You are the best. Thanks.

**Comment by bailey27** [comment]
I noticed this page comes up high in the search results, so I just want to point at that that there are binary releases and have been for some time.  The releases are here

https://github.com/bailey27/cppcryptfs/releases

**Comment by Kodiman** [comment]
hi, your software is excellent quality. much appreciated. best regards. thanks.
