### ISSUE TITLE
NTFS File permissions of encrypted files corrupted with cppcryptfs 14028 / 14027 and Dokany 1301000

### ISSUE THREAD

**Issue by heikoh81** [bailey27/cppcryptfs#80]
Hi bailey27.

I discovered some serious bugs with
cppcryptfs 14028 / 14027 with Dokany 1301000
on Win10 [Version 10.0.17763.864].

With this combination, NTFS file permissions get corrupted making files inaccessible.
I was able to reset file permissions wih this tool on the encrypted files - not the mounted files:
http://lallouslab.net/2013/08/26/resetting-ntfs-files-permission-in-windows-graphical-utility/

I also encountered an error with Excel, described here:
https://github.com/bailey27/cppcryptfs/issues/70
I think it must be connected to this bug.

I downgraded to cppcryptfs14024 with Dokany 1221000
--> No problems any more, not with file permissions nor with Excel.

I do NOT encounter these problems on SMB Shares,
so I guess there has to be a problem with dokany or cppcryptfs changing file permissions only on NTFS drives.
As NTFS is very common, I find it highly necessary to fix this bug. SMB is not a solution as performance is too slow for database queries...

I'm not a programmer but an end user, so I don't know how to address this issue on the dokany github issues.

Maybe you could make contact with dokany developers.
Please help on this issue.

Greetings,
Heiko

**Comment by heikoh81** [comment]
@bailey27 
I think my problems could be linked to this issue: https://github.com/dokan-dev/dokany/issues/822
I have the same permission problems on the files that cause these problems.
So the root cause could be Dokany, as an combination of older versions work without problems.

**Comment by bailey27** [comment]
This has happened to me a couple of times recently.

The solution for me is to use the -l option to cppcryptfs (e.g. "cppcrypts -lr:\") and keep going down the directory structure until I find the full path the the encrypted file with the bad permissions, then go to it with file manager and change the security settings to full access for myself again.

It happens very rarely for me (only two times so far).  I hope they will fix it or have already fixed it in Dokany.

I see a change in the latest Dokany (described as Kernel - FileNameInformation - Only concat UNCName / DiskDeviceName for network devices) which, from reading the thread https://github.com/dokan-dev/dokany/issues/822 sounds like it could be related.  They started talking about UNC paths in that issue, so it could be it.

I'll ask them about it.

I'll so build a new cppcryptfs over the holiday using the latest Dokany 1.3.

**Comment by heikoh81** [comment]
Thanks for your reply, and Merry Christmas!
I also noticed the new dokany version 1.3.1.1000 and installed in.
With cppcryptfs 1.4.0.28 and no special option, I could no longer reproduce the NTFS file permission error.
I did my tests on a local NTFS drive, no UNC paths.

**Comment by bailey27** [comment]
Thanks and Merry Christmas to you too!

I released 1.4.0.29.  I built it with Dokany 1.3.1.1000.  https://github.com/bailey27/cppcryptfs/releases

You should be fine with 1.4.0.28 and Dokany 1.3.1.1000.  I didn't change any Dokany-related code in the new version.

**Comment by heikoh81** [comment]
Still works fine, no more file permission problems on local NTFS encrypted folder so far.
