### ISSUE TITLE
Opening the mount point automatically

### ISSUE THREAD

**Issue by illusoryOne** [bailey27/cppcryptfs#81]
Would it be possible to automatically open the mount point once a folder has successfully been mounted, rather than being required to double click the mount point in the UI?

Thanks for all your hard work & continuous updates, by the way :)

**Comment by bailey27** [comment]
Yes, I could do that.

Would it be ok if it were a setting to always open or not open them?  That would be the easiest way to implement it.

**Comment by illusoryOne** [comment]
Yeah, completely okay. Such a setting would cover my intended use case, at least.

**Comment by bailey27** [comment]
I've released 1.4.1.1 which has this setting.

**Comment by illusoryOne** [comment]
Fantastic. Exactly what I was looking for 👍
