### ISSUE TITLE
[GUI] minimize/close GUI

### ISSUE THREAD

**Issue by madburg** [bailey27/cppcryptfs#83]
Just a small suggestion. The app process must remain running and you have chosen to have it remains in the system tray from my understanding (guessing someone will eventually request an option to run without displaying in system tray).

If I "X" out off the GUI it does not kill the GUI, it closes the GUI and the system tray process remain.
If you however minimize the GUI, it minimizes it to the taskbar, it should close just like when you "X" out of the GUI; as your using a system tray process there is no reason to minimize to taskbar.

**Comment by bailey27** [comment]
I thought it was better to give the user a way of minimizing to the taksbar, minimizing to the system tray, or exiting (using the Exit button on the mount tab).

I prefer to keep it minimized to the taskbar myself.
