### ISSUE TITLE
[Request] Command line list/display as csv friendly format

### ISSUE THREAD

**Issue by madburg** [bailey27/cppcryptfs#84]
Testing Dropbox version history with encrypted files. the "-ld" option is very useful for locating the encrypted file name in order to revert to prior version of a file (seems to work just fine, from limited tests so far).

So my request is can we get an additional command line option to display as csv friendly format.

`-ld:\p, --list=d:\p   list encrypted and plaintext filenames`
e.g. `-lcsvd:\p, --listcsv=d:\p   list encrypted and plaintext filenames`

**Comment by bailey27** [comment]
That wouldn't be hard to add.

However, I'm not sure why it's needed.  If you want to quickly find the encrypted name of a particular file that you know the plain text name of or even just part of it, you could do

```
cppcryptfsctl -ld:\path\to\my\dir  | findstr /i part_of_my_plaintext_file_name
```

**Comment by madburg** [comment]
Agreed for the one offs, and not urgent as one can delimit on => for the time being. but was thinking around a quick method to dump all into a spreadsheet for comparisons (against source), etc.

**Comment by bailey27** [comment]
It's going to be easy to do this.  I'll try to get it done soon.

**Comment by bailey27** [comment]
I just released a new version with csv output as an option (--csv or -C).
