### ISSUE TITLE
Question about number of threads

### ISSUE THREAD

**Issue by null-python** [bailey27/cppcryptfs#97]
Is there any advantage/disadvantage to using 14 threads versus 5 threads if you have a fast CPU?

**Comment by bailey27** [comment]
If you've got 14 or more cpus (either actual cores are hardware threads) and you have 14 or more threads trying to do i/o with a cppcryptfs filesystem at the same time, then it would help performance to use 14 threads (which is the highest value Dokany supports).  

If only one five threads or less are doing i/o at a time, then it won't make any difference.

**Comment by null-python** [comment]
thank you for the clarification
