### ISSUE TITLE
git does not work inside mounted volume

### ISSUE THREAD

**Issue by null-python** [bailey27/cppcryptfs#99]
git clone does not work inside a mounted volume. The error is 

> error: unable to append to '.../.git/logs/refs/remotes/origin/HEAD': Bad file descriptor
> fatal: update_ref failed for ref 'HEAD': cannot update the ref 'HEAD': unable to append to '.../.git/logs/HEAD': Bad file descriptor

If you git clone outside the volume, transfer it into the volume, and try to commit something the error is

> fatal: cannot update the ref 'HEAD': unable to append to '.git/logs/HEAD': Bad file descriptor

I saw this https://github.com/bailey27/cppcryptfs/issues/39 but it doesn't seem to have a solution.

Cryptomator seems to have similar issues as seen here https://github.com/cryptomator/cryptomator/issues/753

**Comment by bailey27** [comment]
I tried what you did (cloned cppcryptfs to an unencrypted directory on C: then moved it with explorer to an encrypted drive and made a change, checked in and pushed).  I worked for me, so I don't know what to say.

**Comment by null-python** [comment]
are you able to clone this repo inside a mounted volume?

https://github.com/null-python/test-project

https://github.com/null-python/test-project.git

**Comment by bailey27** [comment]
Yes, I can clone it using both the url without the .git and the one with it.

```
K:\git>git clone https://github.com/null-python/test-project
Cloning into 'test-project'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 35 (delta 7), reused 30 (delta 5), pack-reused 0
Unpacking objects: 100% (35/35), done.

K:\git>rd /s test-project
K:\git\test-project\* : Are you sure (Y/N)? Y

K:\git>git clone https://github.com/null-python/test-project.git
Cloning into 'test-project'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 35 (delta 7), reused 30 (delta 5), pack-reused 0
Unpacking objects: 100% (35/35), done.
```

I also tried it in the root directory, and it worked.   I also tried using a filesystem mounted using an empty ntfs directory instead of a drive letter, and that worked too.

**Comment by null-python** [comment]
I tried it again but same error.

```
User@... MINGW64 /h/Programming
$ git clone https://github.com/null-python/test-project
Cloning into 'test-project'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 35 (delta 7), reused 30 (delta 5), pack-reused 0
Receiving objects: 100% (35/35), done.
Resolving deltas: 100% (7/7), done.
error: unable to append to 'H:/Programming/test-project/.git/logs/refs/remotes/origin/HEAD': Bad file descriptor
fatal: update_ref failed for ref 'HEAD': cannot update the ref 'HEAD': unable to append to 'H:/Programming/test-project/.git/logs/HEAD': Bad file descriptor

User@... MINGW64 /h/Programming
$ git clone https://github.com/bailey27/cppcryptfs.git
Cloning into 'cppcryptfs'...
remote: Enumerating objects: 372, done.
remote: Counting objects: 100% (372/372), done.
remote: Compressing objects: 100% (239/239), done.
remote: Total 6271 (delta 247), reused 228 (delta 133), pack-reused 5899
Receiving objects: 100% (6271/6271), 5.56 MiB | 578.00 KiB/s, done.
Resolving deltas: 100% (4570/4570), done.
error: unable to append to 'H:/Programming/cppcryptfs/.git/logs/refs/remotes/origin/HEAD': Bad file descriptor
fatal: update_ref failed for ref 'HEAD': cannot update the ref 'HEAD': unable to append to 'H:/Programming/cppcryptfs/.git/logs/HEAD': Bad file descriptor

```
Could it be a problem with my cppcryptfs settings? Here's what they are. I tried changing # of threads and buffer size around but doesn't seem to have an effect. 

![image](https://user-images.githubusercontent.com/16840836/82850953-4072be00-9ecc-11ea-8e3d-2cd5b905e804.png)

![image](https://user-images.githubusercontent.com/16840836/82850985-554f5180-9ecc-11ea-93ad-1f958d5b1041.png)

**Comment by bailey27** [comment]
I think your settings shouldn't affect the behavior at all.  I use the defaults.

I think the saved passwords setting for sure couldn't possibly affect it.

![image](https://user-images.githubusercontent.com/17813578/83328574-fa15ba00-a251-11ea-8628-9a403aa39b3c.png)

**Comment by null-python** [comment]
I tried it with the default settings but got the same issue. I was wondering if it could be an issue with admin. Are you running cppcryptfs and the terminal as non-admin?

Something else that was interesting was after enabling the recycle bin I got a different error.

    User@... /h/Programming
    $ git clone https://github.com/null-python/test-project
    Cloning into 'test-project'...
    fatal: Invalid path 'H:/Device/Volume{d6cc17c5-173f-4085-bce7-964f1e9f5de9}/Programming/test-project': No such file or directory

    User@... /h/Programming
    $ git clone https://github.com/bailey27/cppcryptfs.git
    Cloning into 'cppcryptfs'...
    fatal: Invalid path 'H:/Device/Volume{d6cc17c5-173f-4085-bce7-964f1e9f5de9}/Programming/cppcryptfs': No such file or directory

**Comment by bailey27** [comment]
I updated my git to the latest version and I see the same error your were seeing.

I forgot to check my version before doing that. I haven't updated it in a while.

I'll try to figure out what's going on.

```
K:\git>git clone https://github.com/null-python/test-project.git
Cloning into 'test-project'...
remote: Enumerating objects: 35, done.
remote: Counting objects: 100% (35/35), done.
remote: Compressing objects: 100% (14/14), done.
remote: Total 35 (delta 7), reused 30 (delta 5), pack-reused 0
Receiving objects: 100% (35/35), done.
Resolving deltas: 100% (7/7), done.
error: unable to append to 'K:/git/test-project/.git/logs/refs/remotes/origin/HEAD': Bad file descriptor
fatal: update_ref failed for ref 'HEAD': cannot update the ref 'HEAD': unable to append to 'K:/git/test-project/.git/logs/HEAD': Bad file descriptor
```

**Comment by bailey27** [comment]
I found the problem.

git is opening the file with FILE_APPEND_DATA but not FILE_WRITE_DATA, and that doesn't work with how cppcryptfs/gocryptfs operates.

I got it working, but I need to do some more testing before making a new release.

**Comment by bailey27** [comment]
The release with the fix is out.  https://github.com/bailey27/cppcryptfs/releases/tag/1.4.2.2
